### ISSUE TITLE
FYI: all dependencies should be GHC-9.4 compatible now

### ISSUE THREAD

**Issue by phadej** [ekmett/lens#1011]
And I'll be away for the rest of the week, and I will continue with GHC 9.4 stuff when lens (apparently 5.2) is released.

**Comment by RyanGlScott** [comment]
Thanks, @phadej! I'll cut a release within the next couple of days.

**Comment by RyanGlScott** [comment]
I've uploaded [`lens-5.2`](https://hackage.haskell.org/package/lens-5.2) to Hackage.
