### ISSUE TITLE
No accessors are generated when using `NoFieldSelectors` to remove prefixes.

### ISSUE THREAD

**Issue by ncaq** [ekmett/lens#1024]
With the new `NoFieldSelectors` feature from GHC 9.2, we don't have to prefix every single field with a constructor prefix.

However, lens `makeFields` and others expect the field to start with a constructor prefix or `_`, so if I lose the prefix, they won't create the accessor.

Anyway, my workaround is written below, but I think it would be better to generate accessors by default, given the existence of `NoFieldSelectors` in the first place, than to simply generate this function.
I think that making it the target of `makeLenses` means they expect it to generate accessors.

~~~hs
module Control.Lens.TH.NoFieldSelectors (makeLensesId) where

import           Control.Lens
import qualified Data.Char           as C
import           Language.Haskell.TH

-- | `NoFieldSelectors`を有効にした環境では、
-- フィールドにプレフィクスを付けなくて済みますが、
-- lensがアクセサを作る条件を満たさなくなるため雑に許可します。
makeLensesId :: Name -> DecsQ
makeLensesId = makeLensesWith idRules

idRules :: LensRules
idRules = defaultFieldRules & lensField .~ idNamer

idNamer :: FieldNamer
idNamer _ _ field =
  let fieldPart = nameBase field
      classNamePart = case fieldPart of
        x : xs -> C.toUpper x : xs
        []     -> error "field is empty"
  in [MethodName (mkName $ "Has" ++ classNamePart) (mkName fieldPart)]
~~~

**Comment by RyanGlScott** [comment]
I'm not sure that I'd want to change the default behavior of `makeLenses`, but I definitely think that it would be reasonable to include this as an option for those who want to use `NoFieldSelectors`.

**Comment by ncaq** [comment]
Our internal team member pointed out to me that it would be more appropriate behavior to write `makeFieldsId`, so I'm thinking of putting out a PR to add it.
Right now, the default is to add an accessor if there is an underscore.
I just want to make sure that adding a new function is preferable to changing the behavior of an existing function so that it adds an accessor for fields without underscores, right?

**Comment by RyanGlScott** [comment]
Sure, adding a new function would be a fine way to accomplish this.
