### ISSUE TITLE
Build failure with GHC-9.6, mtl-2.3.1 but transformers-0.5

### ISSUE THREAD

**Issue by phadej** [ekmett/lens#1028]
```
% cabal build -w ghc-9.6.1 --constraint='transformers<0.6' --constraint='mtl >=2.3'
Build profile: -w ghc-9.6.1 -O1
In order, the following will be built (use -v for more details):
 - lens-5.2.1 (lib) (first run)
Preprocessing library for lens-5.2.1..
Building library for lens-5.2.1..
[21 of 84] Compiling Control.Lens.Lens ( src/Control/Lens/Lens.hs, /codetmp/lens-5.2.1/dist-newstyle/build/x86_64-linux/ghc-9.6.1/lens-5.2.1/build/Control/Lens/Lens.o, /codetmp/lens-5.2.1/dist-newstyle/build/x86_64-linux/ghc-9.6.1/lens-5.2.1/build/Control/Lens/Lens.dyn_o ) [Control.Comonad package changed]

src/Control/Lens/Lens.hs:1463:29: error: [GHC-39999]
    • Could not deduce ‘Traversable1 (Reverse t)’
        arising from a use of ‘head1’
      from the context: (Traversable1 t, Functor f)
        bound by the type signature for:
                   last1 :: forall (t :: * -> *) a. Traversable1 t => Lens' (t a) a
        at src/Control/Lens/Lens.hs:1462:1-42
    • In the first argument of ‘(.)’, namely ‘head1 f’
      In the second argument of ‘(.)’, namely ‘head1 f . Reverse’
      In the expression: fmap getReverse . head1 f . Reverse
     |
1463 | last1 f = fmap getReverse . head1 f . Reverse
     |                             ^^^
```

Is there something wrong in `semigroupoids-6`?

**Comment by phadej** [comment]
Answer: There is nothing wrong with `semigroupoids-6`

```haskell
#if HAS_FOLDABLE1_TRANSFORMERS
instance Traversable1 f => Traversable1 (IdentityT f) where
  traverse1 f = fmap IdentityT . traverse1 f . runIdentityT

instance Traversable1 f => Traversable1 (Backwards f) where
  traverse1 f = fmap Backwards . traverse1 f . forwards

instance Traversable1 f => Traversable1 (Lift f) where
  traverse1 f (Pure x)  = Pure <$> f x
  traverse1 f (Other y) = Other <$> traverse1 f y

instance Traversable1 f => Traversable1 (Reverse f) where
  traverse1 f = fmap Reverse . forwards . traverse1 (Backwards . f) . getReverse
#endif
```

And we don't have these compat instances anywhere.

But should we have them in e.g. `transformers-compat`? I don't know.

**Comment by RyanGlScott** [comment]
I think it would make sense to add these to `transformers-compat`. Do you mind opening an issue on the `transformers-compat` side?

**Comment by RyanGlScott** [comment]
Oh wait, I missed the fact that this is specifically about `Traversable1`, which is in a library that `transformers-compat` doesn't depend on. That definitely complicates things...

**Comment by phadej** [comment]
@RyanGlScott I was thinking of adding `foldable1-classes-compat` dependency to `transformers-compat`.

Then the instances can be defined uniformly in `semigroupoids`.

**Comment by RyanGlScott** [comment]
I'm a bit confused. `foldable1-classes-compat` doesn't provide `Traversable1`, right? (I might be missing some details of the plan you have in mind.)

**Comment by phadej** [comment]
We don't define `Traversable1` instances in semigroupoids because of missing `Foldable1` instances.

**Comment by RyanGlScott** [comment]
Ah, that is the part that I was missing! Indeed, that plan sounds reasonable.

**Comment by phadej** [comment]
It doesn't work easily, on older GHCs (GHC-8.0 and older)

```
[__0] trying: transformers-compat-0.7.2 (user goal)
[__1] trying: foldable1-classes-compat-0.1 (dependency of transformers-compat)
[__2] next goal: bifunctor-classes-compat (dependency of
foldable1-classes-compat)
[__2] rejecting: bifunctor-classes-compat-0.1 (cyclic dependencies; conflict
set: bifunctor-classes-compat, foldable1-classes-compat, transformers-compat)
```

And the cycle is there due `Data.Functor.Constant` instances.

I'd propose to drop `transformers(-compat)` dependency from `bifunctor-classes-compat`, and move `Constant` (a long deprecated type!) instrances to `transformers-compat`. i.e. changing the dependency graph into

```
bifunctor-classes-compat <- foldable1-classes-compat <- transformers-compat
```

**Comment by phadej** [comment]
A short term solution for this particular problem (i.e. lens) is to make `lens` require new enough `transformers` on GHC-9.6

i.e.

```cabal
if impl(ghc >=9.6)
  build-depends: transformers >=0.6.1
```

**Comment by RyanGlScott** [comment]
Urgh, good catch. Would this mean that we would also have to remove `foldable1-classes-compat`'s dependency on `transformers-compat`?

**Comment by phadej** [comment]
> Would this mean that we would also have to remove foldable1-classes-compat's dependency on transformers-compat?

Yeah. Now I think it's quite heavy change to go through. Easier to just require newer transformers on GHC-9,6 (as in https://github.com/ekmett/lens/issues/1028#issuecomment-1470500735) if `Foldable1 Reverse` etc. instance is needed. In fact that's probably something that can be done already in `semigroupoids`.

**Comment by RyanGlScott** [comment]
I have uploaded [`semigroupoids-6.0.0.1`](https://hackage.haskell.org/package/semigroupoids-6.0.0.1) to Hackage and blacklisted `semigroupoids-6`. I believe this should take care of this, but please re-open the issue if I have forgotten something.
