### ISSUE TITLE
Negative Index onto Text type results in returning first element 

### ISSUE THREAD

**Issue by dvlasits** [ekmett/lens#1029]
The Text data structure returns the first element for all negative indices, when a negative index should be failing as per String I believe:

> ("123" :: String) ^? ix (-1) 
Nothing

> ("123" :: Text) ^? ix (-1)
Just '1'

**Comment by RyanGlScott** [comment]
Yes, I agree. We should check if the index is between 0 and the length of the length of the `Text`, similarly to how we check this for [things like `Seq`](https://github.com/ekmett/lens/blob/479966809048787402adb0ff4d03525b8a65ada6/src/Control/Lens/At.hs#L299-L302).

A similar problem affects the `Ixed` instances for `ByteString` types as well.

**Comment by dvlasits** [comment]
Yes sounds good, happy to try a PR on that front. It seems indices larger are handled correctly, so may only be necessary to check >= 0.

**Comment by RyanGlScott** [comment]
Fixed in #1030.

**Comment by RyanGlScott** [comment]
I've uploaded [`lens-5.2.2`](https://hackage.haskell.org/package/lens-5.2.2) to Hackage with the changes from #1030. Thanks again for the patch!
