### ISSUE TITLE
Skillsmatter video is not online anymore?

### ISSUE THREAD

**Issue by turion** [ekmett/lens#1055]
https://hackage.haskell.org/package/lens links to https://skillsmatter.com/podcast/scala/lenses-compositional-data-access-and-manipulation, but I get "Not Found - This page is unavailable." when I click on it.

**Comment by RyanGlScott** [comment]
If [this](https://old.reddit.com/r/haskell/comments/194muc3/does_anyone_know_whats_going_on_with_skills/) is correct, then SkillsMatter dissolved in 2023. Unless someone has a mirror of the video somewhere, we should just remove this link.

**Comment by ion1** [comment]
```sh
yt-dlp --referer https://skillsmatter.com/podcast/scala/lenses-compositional-data-access-and-manipulation https://player.vimeo.com/video/76506719
```

**Comment by RyanGlScott** [comment]
Ah, https://player.vimeo.com/video/76506719 must be where the video is hosted, then. Sadly, it appears that you can't actually view the video due to its privacy settings. I'm glad that `yt-dlp` works in a pinch to obtain it, but I'd be hesitant to recommend this in the `.cabal` file as the official way to view the video. Nor am I comfortable re-uploading the video somewhere, since I'm uncertain about the copyright status of the video.

**Comment by emilypi** [comment]
[Do itttttt](https://www.youtube.com/watch?v=L397TWLwrUU)

**Comment by ion1** [comment]
Here's a fun hack: go to https://skillsmatter.com/podcast/scala/lenses-compositional-data-access-and-manipulation and enter this into the developer console:

```js
document.body.innerHTML = '<iframe src="https://player.vimeo.com/video/76506719" style="border: none; background: black; position: fixed; top: 0; left: 0; height: 100%; width: 100%;"></iframe>';
```

**Comment by turion** [comment]
See https://discourse.haskell.org/t/haskell-video-archive-call-for-volunteers/8863, there is hope we may recover the video.

**Comment by ekmett** [comment]
As I understand it, the Haskel Foundation now has the old SkillsMatter videos. So when they put that one online in a new location I'd be happy to link to it.

**Comment by ysangkok** [comment]
@endgame mentioned that you can use yt-dlp:

```
% yt-dlp "https://web.archive.org/web/20231104074630/https://www.youtube.com/watch?v=k-QwBL9Dia0"
[web.archive:youtube] Extracting URL: https://web.archive.org/web/20231104074630/https://www.youtube.com/watch?v=k-QwBL9Dia0
[web.archive:youtube] k-QwBL9Dia0: Fetching archived video file url
[web.archive:youtube] k-QwBL9Dia0: Downloading CDX API JSON
[web.archive:youtube] k-QwBL9Dia0: Downloading capture webpage
[web.archive:youtube] k-QwBL9Dia0: Downloading CDX API JSON
[info] k-QwBL9Dia0: Downloading 1 format(s): 22
```

**Comment by RyanGlScott** [comment]
#1077 adds a working link to the video (via archive.org). It's possible that the Haskell Foundation may upload an archived version of the video in the future, but we can consider whether we want to link to that directly in the future. In the meantime, I'd consider this issue fixed now that we have a working link again.
