### ISSUE TITLE
Wiki Derivation:  Make example types more consistent

### ISSUE THREAD

**Issue by sdzx-1** [ekmett/lens#1056]
Hello everyone, I modified part of the sample code on this [page.](https://github.com/ekmett/lens/wiki/Derivation/_compare/4e5045325ebabba57d3d735956321339a6ec66cc) This is done to make the types of examples more consistent.
Here are some explanations:
<img width="282" alt="pic" src="https://github.com/ekmett/lens/assets/63328943/e3856188-ba9e-4068-86ce-501db3ce3181">

**Comment by sdzx-1** [comment]
@RyanGlScott @ekmett

**Comment by RyanGlScott** [comment]
Thanks for the contribution, @sdzx-1!

I don't really have a strong opinion on the order of type variables myself. I think some folks are used to type variables being presented in a certain order—for instance, the type variable `f` is often listed before `g`, as popularized by [`Data.Functor.Compose`](https://gitlab.haskell.org/ghc/ghc/-/blob/cf756a25fdb4feb7ba7db1f10e590c92cd8d7716/compiler/GHC/Utils/Monad/Codensity.hs). Ultimately, I don't think this needs to be a hard-and-fast rule, and the new order has a certain "incremental" intuition behind it that the previous order did not.
