### ISSUE TITLE
New operators not exported by Control.Lens.Operators

### ISSUE THREAD

**Issue by endgame** [ekmett/lens#1067]
These operators, introduced in `lens-5.3`, are not re-exported through `Control.Lens.Operators`:

*    (<>:~): prepend an element to the front via (<>).
*    (<<>:~): ~~append an element to the back~~ prepend an element to the front via (<>).
*    (<|~): cons an element to the front via (<|).
*    (<<|~): cons an element to the front via (<|) and return the result.
*    (|>~): snoc an element to the back via (|>).
*    (<|>~): snoc an element to the back via (|>) and return the result.

`(<<>:~)` appears misdocumented in the changelog: it is actually left-side `<>` and-return-result

Should these lenses also have `<<` variants which return the old value?

Ping @ncaq

**Comment by RyanGlScott** [comment]
Yes, I think we should re-export these from `Control.Lens.Operators` as well.

> `(<<>:~)` appears misdocumented in the changelog: it is actually left-side `<>` and-return-result

Sorry about that! I wrote the `CHANGELOG` after #1058 had landed, so any errors in the `CHANGELOG` are purely my fault. @ncaq, would you be willing to double-check what I wrote and fix any inaccuracies?
 
> Should these lenses also have `<<` variants which return the old value?

Thoughts, @ncaq?

**Comment by ncaq** [comment]
I think it is a good policy to export.

**Comment by RyanGlScott** [comment]
OK. Regarding the `CHANGELOG` mistake, I think I was confused by the Haddocks for `(<<>:~)`:

https://github.com/ekmett/lens/blob/1ce86ea6a05e22e5d7667eadfa34a2aba903ee00/src/Control/Lens/Lens.hs#L1195-L1201

The Haddocks talk about appending an element to the end, but the implementation prepends to the front instead. As such, I think we need to correct both the Haddocks and the `CHANGELOG`.

**Comment by RyanGlScott** [comment]
I've submitted a fix in #1068.

**Comment by RyanGlScott** [comment]
No problem at all, @ncaq. Thank you for your contribution!

**Comment by endgame** [comment]
> Thank you for your time and effort.

And thank you for yours.
