### ISSUE TITLE
Making `Getting` a bit more general?

### ISSUE THREAD

**Issue by johannesgerer** [ekmett/lens#1073]
What would stop us from defining a more general `Getting`?

```
type Getting r s t a b = (a -> Const r b) -> s -> Const r t
```

I have been running into situations were I already have a `g=Lens` that is not simple (i.e. not of the form `Lens s s a a`) and would like to `view` the value, and find myself forced to reimplement it: `getConst . (g Const)`.

**Comment by phadej** [comment]
So you are asking about generalizing the type of `view`. The answer is no, that won't work. See e.g. https://github.com/ekmett/lens/issues/1059#issuecomment-1986046695

**Comment by johannesgerer** [comment]
duplicate of #1059
