### ISSUE TITLE
`GHC.Generics.Lens` is weak and slow compared to `Data.Data.Lens`

### ISSUE THREAD

**Issue by ekmett** [ekmett/lens#114]
GHC.Generics.Lens should expose `uniplate`, `template`, and `biplate` analogues, not just `tinplate`.

Right now `GHC.Generics.Lens` is fairly crippled compared to `Data.Data.Lens`.

It would be informative to:

* Remove the need for Typeable in the `GHC.Generics.Lens` code, reverting to the use of the Generics `Datatype` class as appropriate.

* Duplicate the reasoning from `Data.Data.Lens` that lets that code avoid traversing portions of the structure unnecessarily. Unlike `Data.Data.Lens` this can make more exacting judgments without having to "guess wrong" once first.

**Comment by glguy** [comment]
"Fixed" in 4e01a13f2fe738e77af29e09370a6cbaa74e6af9

**Comment by flip111** [comment]
Might still be worth looking into at some point because GHC.Generics could be faster than Data.Data, see https://github.com/ndmitchell/uniplate/issues/11#issuecomment-253995372

**Comment by glguy** [comment]
Not every use of Data is appropriate for use with GHC.Generics. The speed up isn't magical and relies on things being able to be determined at compile time.
