### ISSUE TITLE
Fundamental issue with Typeable changes in GHC HEAD

### ISSUE THREAD

**Issue by ekmett** [ekmett/lens#296]
We need to change the way we use `reflection` in `Control.Exception.Lens` because we cannot continue to use it to derive a type from a `Prism`.

Oleg sent me a private email with something I think I can use to fix it several months back.

I should be able to make his version `Typeable`.

``` haskell

{-# LANGUAGE MultiParamTypeClasses, FunctionalDependencies, Rank2Types #-}
{-# LANGUAGE FlexibleInstances, ScopedTypeVariables  #-}
{-# LANGUAGE ExistentialQuantification #-}

-- A bit of optimization, using reference cells

module Refs where

import Data.IORef
import System.IO.Unsafe


class Reifies s a | s -> a where
  reflect :: p s -> a

data Cell a s = Cell (a -> ()) (() -> Maybe a) s

-- The argument is s, but not a
-- This internal function should be used carefully!
-- it should not be exported
create_cell :: s -> Cell a s
create_cell s =
  let r     = unsafePerformIO (newIORef Nothing)
      get () = unsafePerformIO (readIORef r)
      set x  = unsafePerformIO (writeIORef r (Just x))
  in Cell set get s


data Z  = Z
data S a = S a

class CELL a s where
    cell :: Cell a s

instance CELL a Z where
    cell = create_cell (undefined::Z)

instance CELL a n => CELL a (S n) where
    cell = create_cell (undefined::(S n))


instance CELL a s => Reifies (Cell a s) a where
    reflect _ = let Cell _ get _ = cell :: (Cell a s) in
                maybe undefined id $ get ()

data Proxy x = Proxy

make_proxy :: a -> s -> Proxy (Cell a s)
make_proxy _ _ = Proxy

-- Select an instance of CELL
select_cell :: CELL a s => a -> s -> Cell a s
select_cell _ _ = cell

-- Given a type a, there may be already selected instance
-- We chose a fresh instance for the given type a

new_cell :: CELL a s => a -> s -> (forall s. CELL a s => Cell a s -> w) -> w
new_cell a s k =
 let c@(Cell set get _) = select_cell a s in
 maybe (k (set a `seq` c)) (\_ -> new_cell a (S s) k) (get ())

{-
-- Alas, this does NOT generate a new type
-- The type of a quantified variable is always ANY
data GenType = forall s. GenType s

gentype = GenType ()
-}

reify :: a -> (forall s. Reifies s a => Proxy s -> w) -> w
reify a k = new_cell a Z (\ (Cell _ _ s) -> k (make_proxy a s))



t1 = reify (1::Int) (\p -> reflect p)
-- 1

t2 = reify (1::Int) (\p -> reflect (undefined `asTypeOf` p))
-- 1

t3 = reify (Just "ok") (\p -> reflect (undefined `asTypeOf` p))
-- Just "ok"


-- Alas, it doesn't quite work: eigenvariable isn't exactly a gensym!

t4 = reify "s1" (\p1 -> reify "s2" (\p2 ->
  reflect (undefined `asTypeOf` p1) ++ reflect (undefined `asTypeOf` p2)))

-- "s1s2"

t41 = reify (1::Int) (\p1 -> reify (2::Int) (\p2 ->
  reflect (undefined `asTypeOf` p1) + reflect (undefined `asTypeOf` p2)))
-- 4

t5 = reify "s1" (\p1 -> reify "s2" (\p2 -> reify "s3" (\p3 ->
  reflect (undefined `asTypeOf` p1) ++
  reflect (undefined `asTypeOf` p2) ++
  reflect (undefined `asTypeOf` p3))))


newtype M s a        =  M a        deriving (Eq, Show)

unM :: M s a -> a
unM (M a) = a

normalize :: forall a s. (Reifies s a, Integral a) => a -> M s a
normalize a = M (mod a (reflect (undefined :: Proxy s)))

instance (Reifies s a, Integral a) => Num (M s a) where
  M a + M b      =  normalize (a + b)
  M a - M b      =  normalize (a - b)
  M a * M b      =  normalize (a * b)
  negate (M a)   =  normalize (negate a)
  fromInteger i  =  normalize (fromInteger i)

test4'  ::  (Reifies s a, Integral a) => M s a
test4'  =   3*3 + 5*5

runModular :: Integral a => a -> (forall s. Reifies s a => M s a) -> a
runModular x m = reify x (\p -> case m `ass` p of M x -> x)
 where
 ass :: M s a -> Proxy s -> M s a
 ass = const

test4   =   runModular (4::Int) test4'
-- 2

test43   =   runModular (3::Integer) test4'
-- 1
```

**Comment by treeowl** [comment]
Is this still necessary and/or desirable? There have been some major changes in `Typeable` since this change.

**Comment by ekmett** [comment]
Yes. It is necessary precisely _because_ of those changes to `Typeable`.

**Comment by ekmett** [comment]
Before we could build a fake `Typeable` instance to make an exception we could catch but not rethrow that magically checked the right properties to let us catch any `Fold`. Nowadays we have to be more clever.

**Comment by treeowl** [comment]
```haskell
answer = yes
   where yes = no?
```
Or did I misunderstand https://github.com/ekmett/lens/commit/cae5884775875ce9a46fb31415af0fb26c77c497 ?

**Comment by ekmett** [comment]
You misunderstood the patch. I backported these changes into `reflection` itself.

**Comment by treeowl** [comment]
I think I may have taken the claim in the docs that this was based on the slow version too seriously. Anyway, having just one version definitely improves matters.

**Comment by ekmett** [comment]
There are actually four versions now: `reify`, `reifyNat`, `reifySymbol` and `reifyTypeable`.

They are all just supplied by the `reflection` package instead of me having `lens` get into the business of `reflection. ;)

**Comment by treeowl** [comment]
Ew. It seems rather unfortunate such are needed. If `reifyTypeable` is slow, shouldn't it be in the "slow" module rather than the fast one, or at least have a note indicating that it's slow?

**Comment by treeowl** [comment]
I must also admit the entire `reifyTypeable` thing strikes me as highly mysterious. Why would one find it useful to have a `Typeable` instance for that phantom variable? Why does the thing need a `Tapeable a` context? It all looks like deep magic.

**Comment by ekmett** [comment]
There is no "slow" module, the slow directory is a backup plan for how to
do this in case ghc radically changed everything.

**Comment by ekmett** [comment]
As for "why it is useful" see `Control.Lens.Internal.Exception` which does evil evil things with it that can't be done without it.

**Comment by treeowl** [comment]
Crazy idea, or maybe not so crazy. Could a hand-built Typeable instance be
magicked up in ghc-prim with help from the compiler to avoid these clever
Olegian horrors?

**Comment by ekmett** [comment]
Even if it could, all that would do is add yet another code path, as I'd
have to maintain the current version for legacy reasons as well as
something magic through ghc-prim with vague unspecified evil behavior, but
I don't really see what such a beast would actually be.
