### ISSUE TITLE
TH support for irrefutable (lazy) lenses

### ISSUE THREAD

**Issue by mboes** [ekmett/lens#467]
**Short version:** I'd like automatic generation of lenses that are lazyer than the default.

**Motivation:** I have the following use case. Imagine that my program has the following configuration parameters:

``` Haskell
data Config = Config
  { _configParamFoo :: Int
  , _configParamBar :: Int
  } deriving (Eq, Show)

makeLenses ''Config
```

I want to crib configuration settings from various sources. A common way to do so is to make `Config` a monoid, but the downside of that is that it unnaturally requires making each _field_ in the monoid a monoid itself. For _required_ configuration parameters, this may not make sense, because for those there are no defaults (i.e. a `mempty`). So instead I parse each source into configuration transformers, of type `Config -> Config`, which are essentially chains of setters. This is a similar idea to diff lists.

I piece configuration transformers together by function composition. But to execute the transformers, I need to apply them to some base `Config` value. Because I don't have any reasonable default value here, I decide to feed the output of the transformers as the input. This (should) work, because transformers never inspect their input, they only override fields. For example:

``` Haskell
gatherConfig :: IO Config
gatherConfig = mfix $ \config -> do
    commandLineOpts <- parse <$> getArgs
    fileOpts <- parse . words <$> readFile "foo.conf"
    return $ config & fileOpts & commandLineOpts
```

The problem is, this doesn't work. The reason is, `makeLenses` generates functions of the form:

``` Haskell
configFoo f config = (\Config{..} -> ...) <$> ...
```

which force the head of the configuration, hence making the body of the `mfix` strict in the `Config` argument, and hence diverges. But this is unnecessary, because in this particular instance there is only one constructor for `Config`, and so an irrefutable pattern would do just as well:

``` Haskell
configFoo f config = (\ ~Config{..} -> ...) <$> ...
```

There's a potential for space leaks here, so I'm not sure whether lenses for single constructor datatypes should be lazy in this way by default (or should they?), but surely the user ought to at least be able to ask for it when (s)he knows that's ok.

**Conclusion:** we should have `makeLazyLenses`, which produces lenses that are more lazy than the conventional lenses.

**Comment by glguy** [comment]
The behavior is changing in 4.8 with 19970fb4e907628738459c2df7350ee062d0da9e

Lazy behavior will be available using a configuration flag `generateLazyPatterns` as implemented in
df8d3a15903c3c935d822ddbbe7704526375d096
