### ISSUE TITLE
How to properly deal with `defaultRules` removed in 4.4

### ISSUE THREAD

**Issue by ppetr** [ekmett/lens#495]
We're using `defaultRules` which has been removed in 4.4. I thought I could use `lensRules` so that our code would work with both 4.4 and older versions, but the type of `lensRules` changed as well. Is there a way how to replace `defaultRules` with something that'd work across all 4.* versions?

**Comment by glguy** [comment]
There's no single way to write the `LensRules` to work across all the 4.* versions. You'll probably need CPP to generate different `LensRules` values depending on the lens version you're using. This can be hidden away in a single module for the project, at least.
