### ISSUE TITLE
mkLensName hack incompatible with backpack / packages keys

### ISSUE THREAD

**Issue by luite** [ekmett/lens#496]
GHC HEAD (7.9) uses package keys instead of version numbers in package names.

Using names from `mkLensName` makes GHC panic. While GHC probably shouldn't do that, it looks like this approach isn't usable anymore, or at least requires some modifications.

See https://ghc.haskell.org/trac/ghc/ticket/9745

**Comment by ezyang** [comment]
Resurrecting this thread, once this bug is fixed I think you guys no longer will need this hack: https://ghc.haskell.org/trac/ghc/ticket/10382

**Comment by glguy** [comment]
This would be wonderful. I hate the way we have to do things now!
