### ISSUE TITLE
Documentation: Is assign in the wrong column in the table?

### ISSUE THREAD

**Issue by mhwombat** [ekmett/lens#514]
In this table: https://github.com/ekmett/lens/wiki/Operators, `assign` is in the fourth column, indicating that it is stateful and returns the updated value. I think it belongs in the third column, with `.=`, since `.=` is an infix version of `assign`. Or have I misunderstood something?

**Comment by glguy** [comment]
Fixed in https://github.com/ekmett/lens/wiki/Operators/ff81952c10bf196c8ca217f30070778563142a78
