### ISSUE TITLE
Memory leaks when using `%~`

### ISSUE THREAD

**Issue by remdezx** [ekmett/lens#515]
Hello!

I keep getting memory leaks when using code like this:

    updateFoo updMethod = do 
        s <- get
        put $ Env.foo %~ updMethod $ s

while this code works fine:

    updateFoo updMethod = do 
        s <- get
        put $ s { Env._foo = updMethod $ Env._foo s }

Any ideas how is that possible? I'm testing memory usage using `ekg`.

**Comment by glguy** [comment]
Currently makeLenses create lazy matching lenses. In my tests you can add a `$!` to the first code to make it behave identically to the second. (So identical in my test that GHC shares a single worker function between the two of them)

````haskell
updateFoo updMethod = do 
    s <- get
    put $ Env.foo %~ updMethod $! s
````

**Comment by remdezx** [comment]
Thank you for explaination and quick response!
