### ISSUE TITLE
Relax lens bound for lens-properties

### ISSUE THREAD

**Issue by tranma** [ekmett/lens#519]
The current lens bound for lens-properties (lens >= 4 && < 4.1) is too strict & out-of-date. At first glance there isn't anything incompatible with the newer lens versions that I can see. Could this restriction be relaxed or updated?

Thanks a lot!

**Comment by tvh** [comment]
Could you maybe make a hackage-release of this?

**Comment by ekmett** [comment]
sure.

**Comment by tvh** [comment]
Same again. Is it likely that the interface of lens will change enough for this to become invalid? If not, could the bound maybe be something like:
```.haskell
    base         >= 4.3 && < 5,
    lens         >= 4   && < 5,
    QuickCheck   >= 2.4 && < 3,
    transformers >= 0.2 && < 0.5
```
In a new hackage release?

**Comment by ekmett** [comment]
Done. I relaxed `lens` to < 5, but not QuickCheck. I control `lens`, so I can ensure that bound is sound.
