### ISSUE TITLE
overM and setM

### ISSUE THREAD

**Issue by yongqli** [ekmett/lens#520]
Do these functions exist already? I cannot find them, and they seem generally useful.

    overM :: Monad m => ASetter s t a b -> (a -> m b) -> s -> m t

    setM :: Monad m => ASetter s t a b -> m b -> s -> m t
    setM setter valM target = do
      val <- valM
      return $ target & setter .~ val
    {-# INLINE setM #-}

What's the easiest way to write `overM`? 

I use `setM` quite a bit as I have a lot of "pure" computations that are stuck inside of a `MonadRandom`.

**Comment by ekmett** [comment]
You can't write them. a setter isn't powerful enough to allow monadic effects.

You can write them with a `Traversal`, that is `overM` is `mapMOf`.

Stick a `const` in the right place and you can write your `setM` as well, but it isn't named as there isn't a named analogue in `Traversable.
