### ISSUE TITLE
Data-Vector-Lens.ordinals uses Data.List.nub

### ISSUE THREAD

**Issue by treeowl** [ekmett/lens#521]
```haskell
ordinals :: [Int] -> IndexedTraversal' Int (Vector a) a
ordinals is f v = fmap (v //) $ traverse (\i -> (,) i <$> indexed f i (v ! i)) $
                            nub $ filter (\i -> 0 <= i && i < l) is where
  l = length v
```

There is no sense in using `Data.List.nub` with something in `Ord`, `Hashable`, `FiniteBits`, etc. One option is `Data.IntMap`, of course.

**Comment by ekmett** [comment]
A trick here is you want the order preserved from the original list, like `nub`, so its a bit tricky to do right. You can write an order-preserving `nub` using a Set or something from Frtiz Henglein's work on discrimination-based partitioning, but it does require a few extra lines. I'd happily take a patch.

**Comment by glguy** [comment]
Candidate implementation?

```haskell
module Nub (ordinalNub) where

import Data.IntSet (IntSet)
import qualified Data.IntSet as IntSet

-- | Return the the subset of given ordinals within a given bound
-- and in order of the first occurrence seen.
ordinalNub ::
  Int   {- ^ strict upper bound -} ->
  [Int] {- ^ ordinals           -} ->
  [Int] {- ^ unique, in-bound ordinals, in order seen -}
ordinalNub l xs = foldr (ordinalNubHelper l) (const []) xs IntSet.empty

ordinalNubHelper :: Int -> Int -> (IntSet -> [Int]) -> (IntSet -> [Int])
ordinalNubHelper l x next seen
  | outOfBounds || notUnique = next seen
  | otherwise                = x : next (IntSet.insert x seen)
  where
  outOfBounds = x < 0 || l <= x
  notUnique   = x `IntSet.member` seen
```

**Comment by ekmett** [comment]
That looks about right. =)

**Comment by treeowl** [comment]
Just saw this; it looks about the same as mine. If you're bothering to split out `outOfBounds`, you might even `outOfBounds = (fromIntegral x :: Word) >= fromIntegral l`, which in this context does the same thing with just one instruction. I'm also not sure if it helps to use ``(`seq` [])`` instead of `const []` and/or `(next $! IntSet.insert x seen)`.

**Comment by glguy** [comment]
If you want to do some benchmarks that show this version is slow, we can make it messy/more performant, but I'd at least like to start with a simpler version.

**Comment by treeowl** [comment]
@glguy, I am quite confident it is much faster (for long lists) than the current one. The unsigned comparison trick is usually a slight win, but indeed unlikely to rise above the noise here. Whether `seq` is necessary or not depends on how well strictness analysis works here; I'd have to pore over Core to say. The clean way to do the unsigned comparison trick is something like this:

```haskell
between :: Int -> Int -> Int -> Bool
between x low high = (fromIntegral x::Word) < fromIntegral high - fromIntegral low

outOfBounds = not $ (x `between`) 0 l
```
