### ISSUE TITLE
lens 4.6.0.1/4.7 and GHC 7.10.1

### ISSUE THREAD

**Issue by dan-t** [ekmett/lens#536]
Am I missing something or why does the Changelog say that `lens 4.6.0.1` adds
compatibility with `base 4.8` but the upper bounds of base in `lens 4.6.0.1`
and `lens 4.7` are `<4.8`?

Greetings,
Daniel

**Comment by ekmett** [comment]
Because it is a typo. =)

**Comment by ekmett** [comment]
Rather, technically what happened was we added support for 4.8 as it existed at the time, because a lot of work on ghcjs, etc. uses lens even against HEAD versions of GHC, and it turned out to be incorrect for the shipped version of base 4.8.

**Comment by dan-t** [comment]
Ok, so if I want to support GHC 7.6.x/7.8.x/7.10.1 I've to set 4.8 as the
lower bound of the lens library, right?

Thanks!

**Comment by ekmett** [comment]
Well, you can set a lower bound on lens, just so long as your upper bound includes a lens version that will it. `cabal` will pick appropriately based on the set of all constraints involved.

**Comment by dan-t** [comment]
Got it, because of `base 4.8` `cabal` want ever pick a `lens` version lower than `4.8` for `GHC 7.10.1`.

**Comment by ekmett** [comment]
Yep!
