### ISSUE TITLE
Using _head with Data.List.NonEmpty

### ISSUE THREAD

**Issue by epeld** [ekmett/lens#537]
Hey,
I am new to the lenses concept but this appears odd to me:

> _head .~ 45 $ 1 :| []
1 :| []

>  _head .~ 45 $ 1 :| [2]
45 :| [2]

I would expect:
> _head .~ 45 $ 1 :| []
45 :| []

is this a bug or am I missing something?

**Comment by ekmett** [comment]
We probably should consider removing the instance for `NonEmpty`.

Using `_head` requires you to be able to `uncons`. And you can't `uncons` on NonEmpty unless you have at least 2 elements.

The function here is doing the only thing it can do.

**Comment by ekmett** [comment]
For a while the `Cons` class had more arguments, then we could talk about things changing types as you `cons`'d, `uncons`'d, took `_head`, `_tail`, etc.

**Comment by epeld** [comment]
OK thanks for the quick reply.

Would you mind showing me how I could implement a less generic _head that works on NonEmpty and behaves the way I expect?

**Comment by ekmett** [comment]
```haskell
_head :: Lens' (NonEmpty a) a
_head f (a :| as) = (:| as) <$> f a

_tail :: Lens' (NonEmpty a) [a]
_tail f (a :| as) = (a :|) <$> f as
```

**Comment by epeld** [comment]
Great! Thanks again :)

**Comment by ekmett** [comment]
With HEAD you can shorten that to

```haskell
_head = _Wrapped._1
_tail = _Wrapped._2
```

but we probably won't release that any time soon.
