### ISSUE TITLE
Traversing polymorphic tuples

### ISSUE THREAD

**Issue by jdnavarro** [ekmett/lens#538]
This works fine:
```haskell
>>> import Text.Read (readMaybe)
>>> traverseOf each readMaybe ("12","34","56")  :: Maybe (Int,Int,Int)
Just (12,34,56)
```

but this doesn't typecheck:
```haskell
>>> traverseOf each readMaybe ("12","34","56")  :: Maybe (Int,Int,Float)

<interactive>:22:12:
    Couldn't match type ‘Int’ with ‘Float’
    In the first argument of ‘traverseOf’, namely ‘each’
    In the expression:
        traverseOf each readMaybe ("12", "34", "56") ::
          Maybe (Int, Int, Float)
    In an equation for ‘it’:
        it
          = traverseOf each readMaybe ("12", "34", "56") ::
              Maybe (Int, Int, Float)
```

I also tried with `let readMaybe' = undefined :: String -> forall a. Read a => Maybe a`, but it doesn't type check.

At the IRC channel I was suggested to use `bitraverse` which works for 2-tuples:
```haskell
>>> import Data.Bitraversable 
>>> bitraverse readMaybe readMaybe ("12","34") :: Maybe (Int, Float)
Just (12,34.0)
```
The documentation for  [`each`](https://hackage.haskell.org/package/lens-4.9/docs/Control-Lens-Each.html) says
> Extract each element of a (potentially monomorphic) container.

Is it unfeasible, or not desired for some reason, to support polymorphic containers, at least in the case of tuples?

**Comment by bennofs** [comment]
As you can already see in your example, you had to pass your traversal function twice to bitraverse. This also cannot be avoided, since bitraverse must use the traversal function at two different types. But we don't have such a thing currently for lenses or traversals! They only take one traversal function. So it's impossible to implement each that it would work like you want.

**Comment by jdnavarro** [comment]
Thanks for the explanation. I'll wrap the types I want to convert in a single type and work with lists where everything works fine.
