### ISSUE TITLE
"Not in scope" when referring to code after a lens

### ISSUE THREAD

**Issue by mhwombat** [ekmett/lens#542]
Recently I've noticed some strange "Not in scope" errors in modules that contain lenses, when referring to a function defined later. Here's a minimal example.

    {-# LANGUAGE TemplateHaskell #-}
    module MyModule where

    import Control.Lens

    a :: IO ()
    a = do
      b
      -- and some other stuff

    data Stuff = Stuff
      {
        _something :: Int
      }
    makeLenses ''Stuff

    b :: IO ()
    b = do
      -- some stuff
      return ()

The error I get is:

    amy.hs:6:3: Not in scope: ‘b’

If I remove the lens stuff (`data Stuff = Stuff .. makeLenses ''Stuff`), it compiles without errors. This may be something I'm doing wrong, but the error message is confusing.

**Comment by neongreen** [comment]
It's a [known problem with Template Haskell](http://stackoverflow.com/a/20877030/615030).

**Comment by glguy** [comment]
This is how Template Haskell works. Here's a quote from the User's Guide https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/template-haskell.html :

Top-level declaration splices break up a source file into delcaration groups. A declaration group is the group of declarations created by a top-level declaration splice, plus those following it, down to but not including the next top-level declaration splice. The first declaration group in a module includes all top-level definitions down to but not including the first top-level declaration splice.

Each declaration group is mutually recursive only within the group. Declaration groups can refer to definitions within previous groups, but not later ones.
