### ISSUE TITLE
An `Iso` for lazy to strict bytestring/text

### ISSUE THREAD

**Issue by andrewthad** [ekmett/lens#547]
In the Data.ByteString.Lens and Data.Text.Lens modules, would you mind adding these:

    strictBytes :: Iso' LByteString.ByteString ByteString                                                 
    strictBytes = iso LByteString.toStrict LByteString.fromStrict

    strictText :: Iso' LText.Text Text
    strictText = iso LText.toStrict LText.fromStrict

This is straight from some code I use, so you would probably want to adjust it to use whatever qualified import names for `Data.ByteString.Lazy` and `Data.Text.Lazy` you use.

**Comment by cchalmers** [comment]
There's already a [`Strict`](https://hackage.haskell.org/package/lens-4.11/docs/Control-Lens-Iso.html#t:Strict) class in `Control.Lens.Iso` for this.
