### ISSUE TITLE
New Lens versions cannot be installed with either trifecta or zippers

### ISSUE THREAD

**Issue by wdanilo** [ekmett/lens#549]
Lens library `> 4.9.1` requires `semigroupoids == 5.*` where `trifecta` needs (indirectly) the `4.*` one. Simmilar situation is with the dependency of `profunctors == 5.*` in Lens and `profunctors == 4.*` in zippers.

**Comment by glguy** [comment]
This issue with zippers and reducers is already filed against the correct packages.

https://github.com/ekmett/zippers/issues/9
https://github.com/ekmett/reducers/pull/20
