### ISSUE TITLE
Connection to other "lenses"?

### ISSUE THREAD

**Issue by vcunat** [ekmett/lens#562]
Hello. A curious question (not really an "issue").

There's another project that transforms data with "lenses" [1]. I've read about that one and this one only superficially until now, and there were so similar (at first blush) that I thought they were the same thing. Now I look deeper and I can't see any cross-linking at all, so the projects seem independent. Yet, I still feel it would be a too great coincidence if they are completely unrelated. Any idea about this?

[1] http://www.seas.upenn.edu/~harmony/

**Comment by vcunat** [comment]
Ah, I think the whole connection is likely just through this meaning of "lens" as [bidirectional transformation](https://en.wikipedia.org/wiki/Bidirectional_transformation).

I'm closing this, but I'll still be grateful for any relevant feedback.

**Comment by ekmett** [comment]
What we call a "lens" is what Benjamin Pierce, author of Boomerang, calls a "very well-behaved lens".

After defining that, his work went off in another direction, seeking a different set of generalizations by variously removing laws or adding in different consistency conditions: well-behaved lenses, edit lenses, symmetric lenses, etc.

We on the other hand took the lens definition there and started playing with it in its own right, and arrived at a different set of generalizations: traversals, folds, getters, setters, isos, equalities, prisms, etc. The major difference is that in one sense all of these constructions can be seen as using the exact same generalized set of laws, and that we don't get stuck on hard computational problems trying to work with them.

**Comment by vcunat** [comment]
I see. Perchance, could you recommend some good introductory sources for lenses (bidirectional transformations) in general, a survey probably?

I'm a theoretical computer scientist (coincidentally knowledgeable in functional programming) trying to solve some vague practical problems. Lens-like transformations on trees seem very promising, but it's difficult to navigate in those dozens of related papers (and FP-based implementations are likely unsuitable for this application).

**Comment by ekmett** [comment]
Hrmm, the bidirectional transformation community (ox [BX community](http://bx-community.wikidot.com/) as they call themselves) has a workshop and conference where they meet up each year. They might be able to point you in a better direction. I don't know of a good overall introduction to the design space of BX, though. 

Lenses were sort of invented in parallel in a lot of areas: the notion of a functional reference, the view-update problem for databases, synchronizing multiple systems that may each be considered the "master" for a source of data, etc. all tie back to the same notion of (or a slight variations on) a `lens`, so it ultimately comes down to what portion of that design space you want to explore.

You're welcome to join the #haskell-lens channel on irc.freenode.net and chat with folks. There are usually 100-200 people in there at any point in time and they are almost all reasonably well acquainted with the notion of lenses and how they work, and a number of us in there are acquainted with what has been done in related spaces.

**Comment by vcunat** [comment]
I knew the BX page and workshop, but still, thanks a lot for these suggestions! I didn't think of IRC.
