### ISSUE TITLE
Undeclared dependency on `unordered-containers >= 0.2.4`

### ISSUE THREAD

**Issue by bergey** [ekmett/lens#564]
`lens-4.11.1` uses `HashMap.mapWithKey` which was introduced in `unordered-containers-0.2.4`.  Can we get a Hackage revision that bumps the lower bound?

I'm running into this when [testing with old HP](https://travis-ci.org/diagrams/diagrams-lib/jobs/71152540).  With the lower bound changed, cabal picks `lens-4.11`, which seems OK to me.  lens HEAD has the same use of `HashMap.mapWithKey`, so I assume the 2 intervening releases are also affected.

**Comment by glguy** [comment]
I've updated lens-4.11.1, lens-4.12, and lens-4.12.1 on hackage

**Comment by bergey** [comment]
Thanks!
