### ISSUE TITLE
define (%@~) using iover

### ISSUE THREAD

**Issue by tphyahoo** [ekmett/lens#572]
http://ekmett.github.io/lens/src/Control-Lens-Setter.html#%25%40~

claims 

('%@~') ≡ 'iover'

It would be nice, and easier to believe, if this was enforced in the code. The types are the same but the definitions are not (obviously) equivalent. Though clearly they are equivalent if you scrutinize the code a bit.

Currently 

l %@~ f = l %~ Indexed f

and

iover l = over l .# Indexed

The previous definition of (%@~) could be left as a comment, if it is insightful or helpful. (I am not sure if it is.)

Generally I think the operator synonyms should be explicitly defined as the non-operator function they are emulating. This is usually the case, but we deviate here.

This would also make https://github.com/ekmett/lens/wiki/Operators easier to maintain.

**Comment by ekmett** [comment]
We have a general policy of not writing combinators in terms of other combinators if we can avoid it.

It becomes easier believe equations like that that are written as comments, but it comes at a cost of requiring the user to hold in their head an explosion of local names. By the time they figure out what any one thing does, they've lost the thread.

We broke this rule when we build the ifoo combinators in terms of the base foo combinators -- and we've actually paid a price for that fact in some places. The foo combinators are a bit too general and there are some bits of code that should work monomorphically with them that just don't.
