### ISSUE TITLE
make definition of (^.) flip view, or explain the difference.

### ISSUE THREAD

**Issue by tphyahoo** [ekmett/lens#573]
Documentation claims ^. is "the same operation as view with the arguments flipped"

https://github.com/ekmett/lens/blob/master/src/Control/Lens/Getter.hs

Types seem to agree.

> :t flip view
flip view :: b -> Getting a b a -> a
 > :t (^.)
(^.) :: s -> Getting a s a -> a

But the definitions are distinct.

(^.) :: s -> Getting a s a -> a
s ^. l = getConst (l Const s)

view :: MonadReader s m => Getting a s a -> m a
view l = Reader.asks (getConst #. l Const)

can we just define

(^.) = flip view

perhaps leaving the previous definition as a comment for documentary purposes?

I think in this case the definitions might actually be distinct, because view depends on #., which depends on Data.Profunctor.Unsafe for performance reasons.

**Comment by ekmett** [comment]
We're currently deliberately _not_ implementing combinators in terms of each other. Doing so favors relating combinators to each other over the user actually drilling down to figure out what the combinator actually does.

**Comment by tphyahoo** [comment]
Since view depends on (unsafe?) #. and the operator version doesn't (at least not obviously), I'm actually having trouble convincing myself they are the same function. 

In the case of bug 572 I was able to easily convince myself, but not here.

Are they in fact not operationally equivalent? Possibly?  If so, how about changing the documentation to

    (^.) is semantically equivalent to 'flip view', but is defined differently and may have different operational qualities. See "operators versus combinators" page on github.com/ekmett/lens wiki. 

And add this page to wiki explaining the distinction so you don't have to repeat this for every method in the haddock. Or point to relevant ml thread or whatever.

Meanwhile I have been editing https://github.com/ekmett/lens/wiki/Operators, using "/" to indicate where operator and combinator are equivalent to each other.  I started submitting issues when I started having trouble convincing myself of 100% equivalence in some cases.  

It seems like we have following possibilities:

-- explicit equivalence in definition (I understand, not the policy)
-- obvious equational equality, like for bug 572
-- nontrivial equivalence, such as (I would argue) for view versus (^.)

Even the types look different if you view unflipped in ghci.  

Prelude Control.Monad.Reader Control.Lens> :t view
view :: MonadReader s m => Getting a s a -> m a
Prelude Control.Monad.Reader Control.Lens> :t (^.)
(^.) :: s -> Getting a s a -> a

where the reader constraint is present for the operator but not the combinator.  (Is this a ghc bug?)

That, and the #. rabbit hole were enough to leave me scratching my head in this case.

**Comment by ekmett** [comment]
```haskell
(^.) = flip view
```

When you get done inlining and eta-reducing all the things, this is true.

This does not mean that `view = flip (^.)`!

**Comment by ekmett** [comment]
```haskell
flip f a b = f b a
```

`flip view`

requires `view` to be a function of _two_ arguments. 

```haskell
view :: MonadReader s m => Getting a s a -> m a
```

thus requiring `m = (->) s`.

`view` is more powerful than (^.) because it can be used in more situations, e.g. in a monad-transformer stack to access the environment.

**Comment by tphyahoo** [comment]
I see.

I also noticed what I thought was a discrepancy in the documentation, but now I think might have been deliberate.

view: View the value pointed to by a Getter, Iso or Lens or the result of folding over all the results of a Fold or Traversal that points at a monoidal value.

(^.): "View the value pointed to by a 'Getter' or 'Lens' or the result of folding over all the results of a 'Control.Lens.Fold.Fold' or 'Control.Lens.Traversal.Traversal' that points at a monoidal values."

^. version leaves off Iso in the haddock.  Is that an oversight, or is it actually different, and missing the Iso instance?

**Comment by ekmett** [comment]
We're rather inconsistent on documenting `Iso`. 

We typically put enough instances in in the intuition section for folks to figure out the pattern and then leave off. Otherwise we'd have 40+ signatures for every function and the purpose would be lost on completionism. 

I have no strong preference there.

**Comment by tphyahoo** [comment]
Since (per your comment) the view method is constrained to 

m = (->) s

wouldn't it be the (^.) operator that can be used in more contexts? (Since it's unconstrained)

**Comment by ekmett** [comment]
As for `(#.)` the distinction doesn't matter here.

```haskell
s ^. l = getConst (l Const s)
view l = Reader.asks (getConst #. l Const)
```

```haskell
flip view s l = -- def flip
view l s = -- def view
Reader.asks (getConst #. l Const) s = -- def asks
id (getConst #. l Const) s = -- def id
(getConst #. l Const) s = -- def (#.)
coerce (l Const) s = -- effect of coerce
getConst (l Const s) = 
s ^. l
```

**Comment by tphyahoo** [comment]
Or is it the case that the constraints enable the type solver to figure out how to use view in more contexts?

**Comment by ekmett** [comment]
Your reasoning is backwards.

`(^.)` incurs the constraint. `view` doesn't care.

```haskell
foo :: (MonadState (Int,Double) m, MonadReader (String,Bool) m) => m (Int, Bool)
foo = do
  x <- query _1
  y <- view _2
  return (x,y)
```

here `m` is more interesting.

**Comment by ekmett** [comment]
`view` works for many `MonadReader` instances and `(->) s` is only one of them.

**Comment by tphyahoo** [comment]
ok I misundertood your comment 

"flip view requires view to be a function of two arguments."

 but now it's clear.

**Comment by ekmett** [comment]
In any event we deliberately don't define (^.) in terms of view explicitly to avoid encumbering the user of a very simple combinator:

```haskell
s ^. l = getConst (l Const s)
```

which needs nothing other than bog standard Haskell 98 and `base` with the internals of Data.Profunctor and `Control.Monad.Reader.Class`:

```haskell
view l = Reader.asks (getConst #. l Const)
```

and we define `view` in this more esoteric way to avoid eta-expansion of the argument we supply to `asks` for efficiency.

**Comment by tphyahoo** [comment]
Perhaps the documentation could replace

"This is the same operation as 'iview' with the arguments flipped."

with

(^.) is semantically equivalent to 'flip view' but is strictly less powerful.  

or 

The (^.) operator is semantically equivalent to 'flip view' but is strictly less powerful than the view base combinator.

(if you like the "operator" vs "base combinator" jargon.)

This could be fleshed out later with why it's less powerful, but for now just explicitly noting that there is a difference would help make things a lot clearer.

**Comment by tphyahoo** [comment]
It also wouldn't hurt to include the equational proof from above, since you've already paid the cost. 

Not worth doing for every operator of course, but a few examples to get the ball rolling...

**Comment by ekmett** [comment]
That equational proof is rather long winded for a fairly direct result. 

I wrote it out in that form to beat home the equivalence in response to your challenge to its correctness. =P

It is longer than the implementations by an order of magnitude. I'm not in a hurry to force people to wade past it to get to the real content.

**Comment by tphyahoo** [comment]
Fair enough, but how about a wording tweak?

**Comment by ekmett** [comment]
I don't particularly care one way or the other. 

A small patch that clarified the wording there would go in pretty easily.

**Comment by tphyahoo** [comment]
Cool.  Are you ok with "Slightly more fleshed out alternative wording:" above?

**Comment by ekmett** [comment]
> (^.) is only compatible with 'm a ~ s -> a' , whereas view can work with anything that satisfies 'm a ~ MonadReader s m => m a'.

is pretty messy. You're using (~) there between things where the constraints don't quite work.

**Comment by bitemyapp** [comment]
:bee:ting a :skull: :horse:

**Comment by tphyahoo** [comment]
How about 

(^.) is only compatible with 'instance MonadReader r ((->) r)' while view can be used with any instance of MonadReader?

bitemyapp, fair enough. I'm just about done here.

**Comment by bitemyapp** [comment]
@tphyahoo Not trying to be mean, but

> 	tphyahoo opened this issue 2 hours ago

is an outsized amount of time for what this issue has or will accomplish.

**Comment by ekmett** [comment]
Note that there is already a longwinded section in the documentation on view explaining precisely how all this works, on the combinator which has the more general definition.

**Comment by tphyahoo** [comment]
Yeah, I guess it's clear enough from the type signature. 

Sorry for the spam.

In my defense, if (^.) had been defined in terms of flip view, I wouldn't have wondered if there was something voodoo going on.

The above equivalence proof may be "trivial" if you're in the trenches, but when the equivalence wasn't immediately obvious from the source code it was enough to throw me off the scent, especially when I saw that #. was defined in an unsafe namespace.

Of course now I understand.

**Comment by neongreen** [comment]
@tphyahoo I think that novice users of lens don't even know that `view` is more general than `^.`, and more experienced users will be quite satisfied with the explanation provided in the docs for `view`.

I'm usually very dissatisfied with documentation we have, but *this particular choice* looks fine to me.

As for the “lie” contained in “the same operation as `view` with the arguments flipped” (which can lead people to believe that the definitions are the same, while they're not), I have a feeling that “the source is a good companion for the docs” is a notion that is simply not applicable to lens (which probably should be noted somewhere in big bold red letters, and not just hinted at by using “≡” instead of “=” everywhere).

**Comment by tphyahoo** [comment]
Yes, I think there should be something that explains what ≡ means.

**Comment by tphyahoo** [comment]
Can it be stated explicitly that “≡" should be read "can be proved equationally equivalent to" ?

**Comment by ekmett** [comment]
There isn't really a good place for that statement; I use this convention across I'd guess something like ~40 packages.

I try to stick to it over = to avoid the appearance of a function definition, which can matter when the arguments might get misread as a pattern match, and the meaning is usually clear from context.
