### ISSUE TITLE
Lensify multiplate

### ISSUE THREAD

**Issue by spacekitteh** [ekmett/lens#578]
So, it seems that Plated only works with non-mutually-recursive data structures. This is rather unhelpful when trying to deal with ASTs. Multiplate seems like it could be re-implemented in terms of lens combinators, but I'm not sure how to go about it.

**Comment by ekmett** [comment]
This doesn't actually work with lens as it exists today.

With the approach taken in `hask`, we can have lenses with arguments in kind `k -> *` and can smuggle the sort information about which mutually recursive data type we are interested through in `k`, but that isn't compatible with the "being compatible with other lens libraries" mission of `lens`.

To do this you'd have to build an entirely parallel suite of combinators that would gain zero benefit from being included in this package, and would be able to reuse none of the current machinery.
