### ISSUE TITLE
wish: something like Control.Lens.Getter.to, but for setters instead of getters

### ISSUE THREAD

**Issue by tphyahoo** [ekmett/lens#582]
I'd like to write something like

    {-# LANGUAGE NoMonomorphismRestriction, LiberalTypeSynonyms #-}
    import Control.Lens
    t1 = view (to snd) (1,2)
    t2 = set _2 3 (1,2)
    -- t3 = set (to snd) 3 (1,2) -- fails, can't deduce Contravariant Identity

and have t3 work.

Is this possible, or does one have to define setting instances for everything to use the lens style?

**Comment by bennofs** [comment]
What you're looking for is `setting`:

```
setting :: ((a -> b) -> s -> t) -> Setter s t a b
```

**Comment by tphyahoo** [comment]
On latest lens (4.13) I have a slightly different type for setting, and a complicated type error for your t3.

    Prelude Control.Lens> :i setting
    setting :: ((a -> b) -> s -> t) -> IndexPreservingSetter s t a b

    {-# LANGUAGE NoMonomorphismRestriction, LiberalTypeSynonyms #-}
    import Control.Lens
    t3 :: (Int,Int)
    t3 = sets (setting (\f (a,b) -> (a, f b))) 3 (1,2)


    Could not deduce (Num (t0 -> f (f1 t)))
      arising from the ambiguity check for ‘t3’
    from the context (Settable f1,
                      Settable f,
                      Num (t2 -> f (f1 t)),
                      Num t2,
                      Num t1)
      bound by the inferred type for ‘t3’:
                 (Settable f1, Settable f, Num (t2 -> f (f1 t)), Num t2, Num t1) =>
                 f (f1 (t1, t))
      at 1.hs:5:1-50
    The type variable ‘t0’ is ambiguous
    When checking that ‘t3’
      has the inferred type ‘forall (f :: * -> *) (f1 :: * -> *) t t1 t2.
                             (Settable f1, Settable f, Num (t2 -> f (f1 t)), Num t2, Num t1) =>
                             f (f1 (t1, t))’
    Probable cause: the inferred type is ambiguous
Failed, modules loaded: none.

**Comment by bennofs** [comment]
Oh sorry, you need to use `set` instead of `sets`, so it should be:

```
t3 = set (setting (\f (a,b) -> (a, f b))) 3 (1,2)
```

**Comment by tphyahoo** [comment]
yup, was just about to correct the above when browser crashed.

thanks.

**Comment by tphyahoo** [comment]
the above can be rewritten with Control.Arrow

    t3 = set (setting Control.Arrow.second) 3 (1,2)

can this be generalized to more lenses?

can we write settingOn function such that

    settingOn snd => setting Control.Arrow.second
    and of course generalizing to a larger class of lenses?
    then we could have 
    t3 = set (settingOn snd) 3 (1,2)

**Comment by bennofs** [comment]
I don't think it can, since the `snd` function provides no way to change the value. So a `settingOn` would have to work purely by depending on the type, but for a pair, there are at least 3 possibilities for a setter: _1, _2 or both. So there is no general type class for this. In this particular case, since `(,) w` is a Functor, you could also use `mapping :: Functor f => Setter (f a) (f b) a b    ->  mapping :: Setter (w,a) (w,b) a b`. If you want to set a field of a data constructor and that field is not strict [quite fragile conditions IMO, and they are not checked], then `upon` from `Data.Data.Lens` does some magic so that you can also write: `set (upon snd) 3 (1,2)`.

**Comment by ekmett** [comment]
> I don't think it can, since the `snd` function provides no way to change the value.

Sure it does. =)

```haskell
>>> :m + Control.Lens Data.Data.Lens
>>> (1,2) & upon snd .~ 4
(1,4)
```

Er.. uh... I'll see myself out.

**Comment by tphyahoo** [comment]
great. so now I'd like to be able to do

    p1 = Person "bilbo" "the shire"
    makeLenses ''Person -- doesn't work
    t6 = upon _name .~ "samwise" $ p1

is there some easy way to derive the Data instance of Person, so this works?

**Comment by ekmett** [comment]
You can use `upon` to hack in and use field accessors for data types that don't support lens, but do support `Data`... when they don't use strict fields for any field that has the same type as the field you are fishing for.

That is a pretty big set of invariants to track.

`upon` is not a serious suggestion and is not based on sound engineering.

**Comment by tphyahoo** [comment]
still, this works, which is nice

	{-# LANGUAGE NoMonomorphismRestriction, DeriveDataTypeable  #-}
	import Control.Lens
	import Control.Arrow (first, second)
	import Data.Data.Lens (upon)
	import Data.Data
	
	data Person = Person {name :: String, address :: String}
	  deriving (Typeable, Data, Read, Show)
	p1 = Person "bilbo" "the shire"
	t6 :: Person
	t6 = upon name .~ "samwise" $ p1

**Comment by ekmett** [comment]
So does 

```haskell
t7 = upon (tail.tail.tail.name) .~ "ly" $ p1
```

**Comment by tphyahoo** [comment]
I integrated examples with to and upon, with appropriate warnings, to 

https://github.com/ekmett/lens/wiki/Operators

**Comment by ekmett** [comment]
`upon` builds a `Lens`, not a `Getter`, so it is kind of in a strange section there.
