### ISSUE TITLE
suggestion: viewover synonym for views, setover synonym for over

### ISSUE THREAD

**Issue by tphyahoo** [ekmett/lens#583]
naming these functions viewover / setover, etc, would emphasize their similarity in use. currently s suffix means one thing in Getters and another completely different thing in Setters. (views versus sets)

Also I don't think views is a very memorable name.

Additionally for %=, the stateful version of over, it would be nice to have a pronouncable name. Assign is the name for just setting value, not updating with function. So: assignover

context: https://github.com/ekmett/lens/wiki/Operators

update, growing list:

views / viewover
iviews / iviewover
uses / useover
iuses / iuseover

over / setover
iover / isetover
(%=)  / assignover
(%@=)  / iassignover 
 
reviews / reviewover
previews / previewover

side note, if sets wasn't already taken we could just do sets = over, and at least the naming convention would be consistent.  but sets is already in use.

**Comment by ekmett** [comment]
`views` and in general the `s` synonym is named to match up with `asks`.

**Comment by ekmett** [comment]
If anything `sets` is really the one that doesn't follow the rule and was more or less just chosen to read like English.

**Comment by ekmett** [comment]
In general I'm not a big fan of making a half dozen aliases for combinators that have other names. That path just doesn't end and results in a less usable state than the one we started in.

**Comment by ekmett** [comment]
The "lensy" version of the name for `%=` would probably be something like `modifying`. I'd readily take a patch adding that and `imodifying` without any problem.

**Comment by ekmett** [comment]
In any event I think you have a rather fundamentally different meaning of `over` in your head than I do, so I'm going to reject this overall request and open a separate issue for `modifying`/`imodifying`.
