### ISSUE TITLE
suggestion: unto as synonym for upon

### ISSUE THREAD

**Issue by tphyahoo** [ekmett/lens#584]
Because upon is sort of like to, but sort of unsafe... 

Because unto is sort of like to ("do unto others") but not quite the same...

(waving hands)

    let unto = upon

lets you have 

     Control.Lens Data.Data.Lens> set (unto snd) "pluto" ("hello","world") == ("hello","pluto")
     Control.Lens Data.Data.Lens> view (unto snd) ("hello","world") == "world"

to can be used instead of unto for view, but not set in the above.

context: https://github.com/ekmett/lens/wiki/Operators

**Comment by tphyahoo** [comment]
contra this suggestion, there are a number of functions (like oncepon) with variations of "upon" in 

http://ekmett.github.io/lens/Data-Data-Lens.html#v:upon

and I don't know if this plays nicely with unto as name.

**Comment by ekmett** [comment]
I think I'd like to stick with the current name.

`un` and `re` have unrelated connotations, especially when we move to pure profunctor lenses and need a second "dual".
