### ISSUE TITLE
explicit Traversal' in typesig of upon

### ISSUE THREAD

**Issue by tphyahoo** [ekmett/lens#585]
http://ekmett.github.io/lens/src/Data-Data-Lens.html#upon

currently has

upon :: forall p f s a. (Indexable [Int] p, Applicative f, Data s, Data a) => (s -> a) -> p a (f a) -> s -> f s

I think this should be Traversal' s a, assuming haddock is true.

**Comment by ekmett** [comment]
The problem is using a rank-2 type synonym and scoped type variables doesn't work well across GHC versions. When that happens you get explicit foralls in the signatures and documentation explaining the real type.
