### ISSUE TITLE
[question] How to make `over`-like operator failing with Nothing on no modified content?

### ISSUE THREAD

**Issue by Heimdell** [ekmett/lens#598]
Standard `over` will ignore lack of content. That is not acceptable for me, since I use zippers and silent write failures could break my code.

The only thing I can figure out is:

```haskell
((check, lens) %~? f) object = do
    object^?check
    return (object & lens %~ f)

modifyFile :: (File -> File) -> (Position -> Maybe Position)
modifyFile f = (focus._OnFile, focus._OnFile) %~? f

getFile :: Position -> Maybe File
getFile pos = pos^?focus._OnFile
```

Seems like the typechecker cannot figure out the intersection of Setter & Getter types.

**Comment by cchalmers** [comment]
Looks like [`failOver`](https://hackage.haskell.org/package/lens-4.12.3/docs/Control-Lens-Traversal.html#v:failover) is what you want.

**Comment by Heimdell** [comment]
Great! It works! Thank you very much!
