### ISSUE TITLE
Documentation on Traversal is confusing

### ISSUE THREAD

**Issue by treeowl** [ekmett/lens#600]
The documentation indicates that "a `Traversal` is not quite a `Fold`," but does not mention that every `Simple Traversal` *is* a `Fold`. This confused me for a few minutes.

**Comment by bitemyapp** [comment]
Confusing or `confusing`? :wink:

**Comment by ekmett** [comment]
Patch welcome.

**Comment by treeowl** [comment]
Patch provided.
