### ISSUE TITLE
Add "Do I need this?" tests for fusion operations

### ISSUE THREAD

**Issue by treeowl** [ekmett/lens#601]
`fusing` and `confusing` re-associate things to improve efficiency. It might be nice to add functions to check whether these operations actually modify a particular traversal.

**Comment by ekmett** [comment]
Such tests would require e.g. an illegal functor instances that counts how many uses of `fmap` you make.

**Comment by treeowl** [comment]
As horrifying as that is, I think it's acceptable for a function whose sole
purpose is to help programmers understand what some pretty freaky functions
do to their code.

**Comment by ekmett** [comment]
I have no problem with adding it to the test suite, etc. but it doesn't really offer much use in the library itself. You can also in theory detect this by looking at the outcome of `magma` today.

**Comment by treeowl** [comment]
The fusion functions are exported from "public" modules, which suggests
that people might want to use them sometimes. Why would it not be useful to
provide quick ways to determine whether it's even worth setting up
benchmarks?

**Comment by ekmett** [comment]
The short version, *any* time you compose two lenses, `fusing` fuses something.

*Any* time you compose two traversals `confusing` fuses something.

The test is visual: Is there a (.) involved? ;)
