### ISSUE TITLE
Should Equality get some of Iso's bling?

### ISSUE THREAD

**Issue by treeowl** [ekmett/lens#604]
```haskell
data StrongExchange a b s t = StrongExchange (s :~: a) (Identity b :~: t)
type AnEquality s t a b =
       StrongExchange a b a (Identity b) -> StrongExchange a b s (Identity t)
type AnEquality' s a = AnEquality s s a a

equality :: (s :~: a) -> (b :~: t) -> Equality s t a b
equality Refl Refl f = f

equality' :: (s ~ a, b ~ t) => Equality s t a b
equality' f = f

withEquality :: forall s t a b r . AnEquality s t a b -> ((s :~: a) -> (b :~: t) -> r) -> r
withEquality eq k =
  case eq (StrongExchange Refl Refl :: StrongExchange a b a (Identity b)) of
    StrongExchange sa bit -> k sa (down bit)

withEquality' :: forall s t a b r . AnEquality s t a b -> ((s ~ a, b ~ t) => r) -> r
withEquality' eq k = withEquality eq (\Refl Refl -> k)
```

Note: any `Equality` can act as `AnEquality`:

```haskell
isit :: Equality s t a b -> AnEquality s t a b
isit f = f
```

**Comment by ekmett** [comment]
Do you have an example of something this makes easier to say?

**Comment by treeowl** [comment]
Frankly, I'm not too clear on what `Equality` itself makes easier to say. It represents evidence of some equalities; these functions move back and forth between different forms of that evidence.

**Comment by treeowl** [comment]
One (potential) point about `withEquality` is that it packages up the evidence so the consumer has the opportunity to ready itself before opening it; I don't know if this is particularly helpful in a lensy context, but being able to delay the introduction of evidence can be very helpful.

**Comment by treeowl** [comment]
I just realized that `StrongExchange` can be cheaper:

```haskell
newtype StrongExchange a b s t = StrongExchange ((s,Identity b) :~: (a, t))
```

**Comment by ekmett** [comment]
Strong exchange can be easier still

```haskell
data Equals s t a b where
  Refls :: Equals s t s t

withEquality :: forall s t a b r . AnEquality s t a b -> ((s ~ a, b ~ t) => r) -> r
```

but this is the same functionality that Identical provides today.

**Comment by ekmett** [comment]
We _have_ to plumb the functions because they are required, the equalities can just be brought into the environment as evidence.

**Comment by treeowl** [comment]
Ha! Somehow I failed to find that entire module, despite explicitly looking
for it.

**Comment by ekmett** [comment]
Closing this out, since the same general functionality is in there.
