### ISSUE TITLE
Equality could be polykinded

### ISSUE THREAD

**Issue by treeowl** [ekmett/lens#605]
This would be a *mildly* breaking change, unless some new names were added. I doubt it would break any actual code. Is there something wrong with this idea that I'm not seeing?

```haskell
{-# LANGUAGE PolyKinds #-}
-- These kinds will be inferred; they're annotated for clarity.
type Equality (s :: k1) (t :: k2) (a :: k1) (b :: k2) = forall p f . p a (f b) -> p s (f t)
type Equality' s a = Simple Equality s a

simple :: Equality' a a
simple f = f

lessSimple :: Equality a b a b
lessSimple f = f

data Identical :: k1 -> k2 -> k1 -> k2 -> * where
  Identical :: Identical a b a b

-- The potentially-breaking change: use Proxy instead of Identity
type AnEquality s t a b = Identical a (Proxy b) a (Proxy b) -> Identical a (Proxy b) s (Proxy t)
type AnEquality' s a = AnEquality s s a a

runEq :: forall (s :: k1) (t :: k2) (a :: k1) (b :: k2) . AnEquality s t a b -> Identical s t a b
runEq l = case l Identical of Identical -> Identical

substEq :: forall (s :: k1) (t :: k2) (a :: k1) (b :: k2) (r :: *) . AnEquality s t a b -> ((s ~ a, t ~ b) => r) -> r
substEq l = case runEq l of
  Identical -> \r -> r

mapEq :: forall (s :: k1) (t :: k2) (a :: k1) (b :: k2) f . AnEquality s t a b -> f s -> f a
mapEq l r = substEq l r

fromEq :: forall (s :: k1) (t :: k2) (a :: k1) (b :: k2) . AnEquality s t a b -> Equality b a t s
fromEq l = substEq l id
```

**Comment by treeowl** [comment]
See #606

**Comment by ekmett** [comment]
Polykinds would work there from 7.6+

**Comment by treeowl** [comment]
That's what I figured. When I tried it, I got a kind error.

**Comment by ekmett** [comment]
Due to Identity being non polykinded?

**Comment by treeowl** [comment]
Unless I goofed it up (always a possibility), I always kept the `Identity`/`Proxy` switch aligned with the `PolyKinds`/not one.

**Comment by treeowl** [comment]
D'you want me to try with 7.6 again? I'm not sure I'll get the git/travis dance right, but I can try.

**Comment by treeowl** [comment]
Oh wait.... that's wrong... it must have failed before there, because 7.6 doesn't have `Proxy`.

**Comment by ekmett** [comment]
i'd prefer to keep all the polykinds stuff tied to 7.6 if i can. makes it easier to figure out the version bounds of different features. 7.6 has Proxy from `tagged`.

**Comment by treeowl** [comment]
OK, I managed to make it polykinded in 7.6, but more so in 7.8+. The only difference is in the definition of `Equality`. In 7.8+, there's a universally quantified kind variable on the RHS; 7.6 can't stand that so I fixed it to `*` there.
