### ISSUE TITLE
Add less-simple Equality

### ISSUE THREAD

**Issue by treeowl** [ekmett/lens#617]
Currently, we have only

```haskell
simple :: Equality' a a
```

I think we should add

```haskell
lessSimple :: Equality s t s t
```

because it can be implemented nicely behind the scenes, but less nicely with the "official" interface.

**Comment by ekmett** [comment]
I'm okay with adding something. Open to other colors for the bikeshed with regards to the name though.

**Comment by xplat** [comment]
refl?

**Comment by treeowl** [comment]
I suppose it would be sufficient to document the fact that

id :: Equality s t s t

**Comment by ekmett** [comment]
I think the fact that `id` is such an equality suffices.
