### ISSUE TITLE
Removing Rift from kan-extensions break current lens

### ISSUE THREAD

**Issue by Heather** [ekmett/lens#627]
https://github.com/ekmett/lens/blob/master/lens.cabal#L196
https://github.com/ekmett/kan-extensions/commit/e1293e7f95639681017f366caba9e0170b655778
https://github.com/ekmett/lens/blob/master/src/Control/Lens/Traversal.hs#L151

**Comment by RyanGlScott** [comment]
It appears that `Rift` will be replaced with `Curried` in the next `kan-extensions` release. I'm hesitant to change `lens` now, though, since you can't get `Curried` from Hackage's `kan-extensions` at the moment.

**Comment by Heather** [comment]
@RyanGlScott I will be glad to be able lens with most recent packages due ghc 8, thank you very much for your support

**Comment by ekmett** [comment]
@Heather GHC 8 support for most things hinges on me doing a new release of `transformers-compat`, that will likely not happen for a couple of days.

**Comment by glguy** [comment]
I've bumped the edward-major number on kan-extensions to 5 since the Rift change breaks packages in the ecosystem.

**Comment by Heather** [comment]
@glguy that's good motion, thanks, then when lens will be reworked it will start from >= 5 ?

**Comment by ekmett** [comment]
I probably won't bump lens to 5.0, just kan-extensions.

**Comment by RyanGlScott** [comment]
Until then, you can use [this branch](https://github.com/ekmett/lens/tree/ghc-8.0) of `lens`, which should work out-of-the-box with GHC 8.0.1-rc1 (assuming you have the right dependencies installed, such as `kan-extensions-5`).

**Comment by Heather** [comment]
@RyanGlScott thanks, I'll test it some later

**Comment by RyanGlScott** [comment]
Fixed in 320cdb3125f0e5b9d79f1421ab9e28d3c95929eb.
