### ISSUE TITLE
Improve TraversableWithIndex for Data.Sequence

### ISSUE THREAD

**Issue by treeowl** [ekmett/lens#629]
It's not possible to do anything about this here yet, but assuming https://github.com/haskell/containers/pull/179 is accepted, the `TraversableWithIndex Int Seq` instance should be changed to `itraverse = Data.Sequence.traverseWithIndex`.

**Comment by treeowl** [comment]
Actually, I was wrong. We *can* do something about it now!

```haskell
itraverse f = sequenceA . D.S.mapWithIndex f
```

should be the best way to do it today.

**Comment by ekmett** [comment]
Sounds good to me.

**Comment by treeowl** [comment]
@ekmett, https://github.com/ekmett/lens/pull/630 should, I think, be the best we can do for now, and I think it's probably sufficiently obvious to merge now. The pull request for `traverseWithIndex` has been accepted upstream, so we'll have to keep an eye on that.
