### ISSUE TITLE
Offer a blind setter for convenience/simplicity

### ISSUE THREAD

**Issue by treeowl** [ekmett/lens#631]
``` haskell
setsBlindly :: (Settable f, Profunctor q) =>
     (b -> q s t) -> (() -> f b) -> q s (f t)
setsBlindly f = sets (\g -> f (g ()))
```

When `q ~ (->)`, this produces a `Setter s t () b`, which collapses `over` into `set`.

**Comment by ekmett** [comment]
I don't like it as the use of () there doesn't follow the family structure, so you can't use this with any actual legal lens arguments, unless b ~ ().
