### ISSUE TITLE
Hackage documentation: front page contains escaped HTML

### ISSUE THREAD

**Issue by afcady** [ekmett/lens#633]
If you go to https://hackage.haskell.org/package/lens and scroll down to the section labeled "Operators" you see HTML tags in the rendered page.  The whole section is like that.

**Comment by tebello-thejane** [comment]
I believe this is an issue either with Haddock, or with Hackage specifically. 

The table renders properly on Github, as well as on Stackage. 

Although, it would be great if the README was made to be compatible with Hackage (by not using HTML tables).

**Comment by ekmett** [comment]
The README was written using github flavored markdown, but the new hackage feature of showing the README only supports vanilla flavored markdown, which doesn't include things like tables.

We can remove the operators section from the README, but this won't fix documentation on old versions, which were retroactively changed to include that document in the hackage UI.

**Comment by afcady** [comment]
It would be a shame to just remove the section, since it works everywhere else.  I found where HTML is disallowed:

https://github.com/haskell/hackage-server/blob/9a051d27fe5648ff7795ef2a95b31e7139cbac02/Distribution/Server/Features/PackageContents.hs#L212

I also found this:

https://github.com/haskell/hackage-server/pull/356#issuecomment-102956799

(Funny, in that discussion (from a year ago), the lens README.md was directly addressed.)

I'm going to go nag https://github.com/haskell/hackage-server about this...

**Comment by ekmett** [comment]
Looks like we've since removed the bit in question.
