### ISSUE TITLE
cut ghc 8.0 compatible lens version :) 

### ISSUE THREAD

**Issue by cartazio** [ekmett/lens#652]
cc @hvr (looks like travis CI now is using an RC4 version of ghc 8.0 now too)

**Comment by cartazio** [comment]
Looks like lens-properties sneaks in as a dependency when using new-build

**Comment by erikd** [comment]
Just hit this myself.

**Comment by ekmett** [comment]
Did we change something to make that the default?

**Comment by erikd** [comment]
Yes, it changed between rc3 and rc4 :(.

**Comment by ekmett** [comment]
Um, wait, was this because of a `cabal` change or a `lens` change?

**Comment by RyanGlScott** [comment]
I think there's two issues at play:

1. There's a `cabal new-build` issue (i.e., new Nix-like functionality in `cabal-install`) that probably isn't `lens`-specific.
2. GHC 8.0.1-rc4 introduced an [API-breaking Template Haskell](http://git.haskell.org/ghc.git/commit/04b70cda4ed006c7e3df40e169550a00aba79524) changed that causes [`lens-4.13.2.1`](http://hackage.haskell.org/package/lens-4.13.2.1) to fail to compile. @cartazio made a PR that fixes this [which was merged](https://github.com/ekmett/lens/pull/648), but hasn't been released to Hackage.

**Comment by ekmett** [comment]
Got it, now the `new-build` comment makes sense to me.

**Comment by cartazio** [comment]
Yeah, I was trying to get lens master to be added into my ci for other code, as a work around till there's a new release, but ran afoul of new cabals new build command getting confused.  @hvr indicated that one work around I could do is create a suitable cabal.project file in my lens checkout, but either way I'm shaving around the real goal: ci working for some code on 8.0 :)

**Comment by hvr** [comment]
@cartazio jfyi, I'm experimenting in #646 with new-build for Travis, since `lens` is one of the few non-trivial projects I have experience and access to...

**Comment by hvr** [comment]
just for the record: `new-build` currently has an implicit default of the (more or less) kind `packages: *.cabal */*.cabal`. If you have bitrotted `.cabal` files in subfolders, you're advised to create an explicit `cabal.project` with at least the content `packages: .` which serves two purposes:

 - `cabal` knows where your project-root is located
 - `cabal` knows that you only care about the `.cabal` location you specified

**Comment by ekmett** [comment]
@hvr: ^- like that?

**Comment by hvr** [comment]
@ekmett yes, like that

**Comment by hvr** [comment]
@ekmett fyi, [ANN: GHC 8.0.1 release candidate 4 available](https://mail.haskell.org/pipermail/ghc-devs/2016-April/011955.html) is officially out now. I.e. a wider user-base will be hitting this problem now.

**Comment by simonmichael** [comment]
Yup, I just hit it. (If it means [this InstanceD error](https://gist.github.com/simonmichael/efd5cc75f3530a26455ecc1a58b1a5a8)).

**Comment by glguy** [comment]
Lens 4.14 is on hackage
