### ISSUE TITLE
Make patterns Data.Complex.Lens total

### ISSUE THREAD

**Issue by Icelandjack** [ekmett/lens#653]
The definitions of `Real` and `Imaginary` 

``` haskell
pattern Real r      = r :+ 0
pattern Imaginary i = 0 :+ i
```

be made

``` haskell
pattern Real :: Num a => a -> Complex a
pattern Real r <- r :+ _
  where Real r =  r :+ 0

pattern Imaginary :: Num a => a -> Complex a
pattern Imaginary i <- _ :+ i
  where Imaginary i =  0 :+ i
```

Currently they are partial, throwing an error when the scrutinee is not `r :+ 0`, `0 :+ i` respectively.

```
>>> let Real a = 1 :+ 2 in a
*** Exception: <interactive>:4:5-19: Irrefutable pattern failed for pattern Real a
```

with my code you get:

```
>>> let Real' a = 1 :+ 2 in a
1
```

**Comment by ekmett** [comment]
The current form has the property that you can always reconstruct with what you match without losing information.

The form you propose has different non-constructor-like semantics.

In general folks expect

```haskell
foo (Bar x) = Bar x
foo y = y
```

to be equivalent to an identity function.

Yours would start catching more stuff in the dragnet and silently killing it, in a place where culturally we don't expect such behavior.

**Comment by Icelandjack** [comment]
Thanks for your input, I responded in the [https://ghc.haskell.org/trac/ghc/ticket/12001#comment:5 trac ticket] and will keep this example in mind.

**Comment by ekmett** [comment]
Choosing to keep the existing semantics for the reasons specified earlier.
