### ISSUE TITLE
Data.Complex.Lens patterns in terms of base functions, move to base

### ISSUE THREAD

**Issue by Icelandjack** [ekmett/lens#654]
``` haskell
pattern Polar m theta <- (view _polar -> (m, theta)) where
  Polar m theta = review _polar (m, theta)
```

could easily be defined in terms of [`polar`](https://hackage.haskell.org/package/base-4.8.2.0/docs/Data-Complex.html#v:polar) and [`mkPolar`](https://hackage.haskell.org/package/base-4.8.2.0/docs/Data-Complex.html#v:mkPolar):

``` haskell
pattern Polar m theta <- (polar -> (m, theta))
  where Polar m theta = mkPolar m theta
```

Following that these patterns could all be moved to `Data.Complex`.

**Comment by ekmett** [comment]
I have no objection to building them out of simpler, more commonly used parts.

I'm not sure it'll be easy to convince folks to add pattern synonyms directly to `base` yet, however. They are a fairly new feature that has been subject to a fair bit of bikeshedding.

**Comment by Icelandjack** [comment]
I agree. Pattern synonyms have a short but tumultuous history but I created a [ticket](https://ghc.haskell.org/trac/ghc/ticket/12001) anyway, it can be added (or not) as the dust settles.

**Comment by ekmett** [comment]
When and if there becomes something we can act on this, please re-open this ticket.
