### ISSUE TITLE
SafeHaskell and Data.Coerce in lens

### ISSUE THREAD

**Issue by int-e** [ekmett/lens#661]
I'm in the process of updating lambdabot to ghc 8.0, and noticed that since a bit over a year now, [Control.Lens.Internal.Coerce](https://github.com/ekmett/lens/blob/master/src/Control/Lens/Internal/Coerce.hs) effectively reexports the (currently marked unsafe) `Data.Coerce` module safely.

Relatedly, [Control.Lens.Iso](https://github.com/ekmett/lens/blob/master/src/Control/Lens/Iso.hs) exports `coerced` which effectively provides the functionality of `Data.Coerce.coerce` as well.

In the Trac ticket https://ghc.haskell.org/trac/ghc/ticket/8827 the ghc folks decided not to trust `Data.Coerce` just yet, so lens is inconsistent with that decision.

Was this a conscious decision? I cannot say that `Data.Coerce` should not be trusted. As far as I can tell, there is a trade-off between forcing library authors that encapsulate unsafe functionality to provide proper role annotations for their abstractions and not having `coerce` functionality available in SafeHaskell. That said I'm probably going to err on the side of safety and avoid `Data.Coerce` reexports in lambdabot, for now; the question is whether the official lens should be changed as well.

**Comment by int-e** [comment]
FWIW, I have produced the following draft patch which I use for running lambdabot without effectively exposing `Data.Coerce.coerce`:

https://github.com/lambdabot/lambdabot/blob/freenode/patches/lens-4.14.patch
(I've patched a few dependencies as well, most notable profunctor and parallel)

I'm still interested in discussing this issue.

**Comment by ekmett** [comment]
I'm open to discussing the placement of `coerced`, but it is quite useful. =/ 

And as you can see we use `coerce` fairly heavily throughout lens. Before we used to `unsafeCoerce` after all, so this is a pretty big step forward. =)

**Comment by int-e** [comment]
I've mulled this over for a bit. I believe what I really want is to be convinced that ```coerce``` is, actually, safe to be trusted. But this github issue is the wrong forum for that.

At this point I don't want to push ```lens``` to distrust ```coerce```, unless somebody (like myself) can identify an actual type safety issue with it, possibly in connection with a common library. Even if such an issue turns up, it'll hopefully be fixable without declaring ```coerce``` untrustworthy.
