### ISSUE TITLE
Order of type variables

### ISSUE THREAD

**Issue by Icelandjack** [ekmett/lens#670]
Ever since 8.0 the order of type variables matters, the argument order is flipped but that doesn't mean the order of types should be:  

``` haskell
>>> :t itoListOf
itoListOf
  :: forall {i} {a} {s}.
     IndexedGetting i (Endo [(i, a)]) s a -> s -> [(i, a)]
>>> :t (^@..)
(^@..)
  :: forall {s} {i} {a}.
     s -> IndexedGetting i (Endo [(i, a)]) s a -> [(i, a)]
```

Thoughts?

**Comment by RyanGlScott** [comment]
Well, first I must ask: is there any problem here? It's true that the order of type variables matters for `TypeApplications`, but for the functions you mention above, I'm not seeing why a particular ordering (other than topologically sorted, as is the case now) would be pertinent. Unless you are thinking of an overarching, consistent ordering for the type variables of all functions in `lens`? If so, please state what you have in mind.

**Comment by Icelandjack** [comment]
I'm looking to start a conversation since type variables are now a part of the API.

Is one ordering preferable? How consistent should it be?

Considering the `*WithIndex` classes where the index is determined by the `Functor`, `Foldable`, ...:

```haskell
itoListOf @Int ifolded :: FoldableWithIndex Int f => f a -> [(Int, a)]

itoListOf @_ @() ifolded :: FoldableWithIndex t f => f () -> [(t, ())]

itoListOf @_ @_ @[_] ifolded :: [t] -> [(Int, t)]
```

yet it is the last type variable.

**Comment by ekmett** [comment]
In some sense the current 'inconsistent' ordering is actually more consistent, in that the variables occur in the natural order they appear in the type of the combinator. Applied consistently, this allows users to reason about it without knowing some magic incantation order for the foralls.

**Comment by glguy** [comment]
I've prefer to be able to rely on the type variables using the default ordering rather than having to memorize the ordering manually assigned to each combinator.

**Comment by ekmett** [comment]
I think I'm going to close this out. We have a rule (natural arg order) that is consistent, even if it isn't optimal for some scenarios, but I think ultimately every rule will be suboptimal for some scenarios.
