### ISSUE TITLE
Ambiguous take and drop

### ISSUE THREAD

**Issue by jakubdaniel** [ekmett/lens#674]
When I compile `lens>=4.14` with `ghc-7.10` I get an ambiguity error in `Control.Lens.Traversal` and `Control.Lens.TH` on usage of the functions `take` and `drop`. The installed version of `containers` is `0.5.8.1`.

**Comment by glguy** [comment]
This appears to be fixed in https://github.com/ekmett/lens/commit/e089254441cf77bac3f6baebdce8fe5d4b3ac8e7

**Comment by glguy** [comment]
The upper bound is being lowered for existing lens on hackage, version 4.15 will be compatible with the new containers release.
