### ISSUE TITLE
Doctests fail to run with Cabal-1.25.0.0

### ISSUE THREAD

**Issue by RyanGlScott** [ekmett/lens#678]
[From a recent Travis build:](https://travis-ci.org/ekmett/lens/jobs/161842886#L631)

```
$ cabal test
Preprocessing test suite 'hlint' for lens-4.15...
Preprocessing library lens-4.15...
Preprocessing test suite 'templates' for lens-4.15...
Preprocessing test suite 'properties' for lens-4.15...
Preprocessing test suite 'hunit' for lens-4.15...
Preprocessing test suite 'doctests' for lens-4.15...
Running 5 test suites...
Test suite hlint: RUNNING...
Test suite hlint: PASS
Test suite logged to: dist/test/lens-4.15-hlint.log
Test suite templates: RUNNING...
Test suite templates: PASS
Test suite logged to: dist/test/lens-4.15-templates.log
Test suite properties: RUNNING...
Test suite properties: PASS
Test suite logged to: dist/test/lens-4.15-properties.log
Test suite hunit: RUNNING...
Test suite hunit: PASS
Test suite logged to: dist/test/lens-4.15-hunit.log
Test suite doctests: RUNNING...

<command-line>:8:0: error:
     fatal error: dist/build/global-autogen/cabal_macros.h: No such file or directory
compilation terminated.
doctests: `gcc' failed in phase `C pre-processor'. (Exit code: 1)
Test suite doctests: FAIL
Test suite logged to: dist/test/lens-4.15-doctests.log
4 of 5 test suites (4 of 5 test cases) passed.
```

This is ultimately due to the same issue as https://github.com/haskell/cabal/issues/3566, but manifesting in a slightly different way.

**Comment by phadej** [comment]
I guess this is related to `Cabal` changes.

**Comment by glguy** [comment]
@RyanGlScott Could you confirm that this is still an issue? I was able to run the doctests with a recent build of the Cabal master branch today.

**Comment by phadej** [comment]
@glguy the fresh cabal master has  implicit `setup-depends: Cabal <1.25`, so yes, it does seem to compile cleanly with recent `Cabal`, but not against `Cabal-1.25`.

It would be nice to check what changes are needed to custom setup.hs to work with next major `Cabal`, but it's a bit tricky. I fail to make `cabal-install` compile lens `Setup.hs` against local copy of `Cabal`. Cannot find a Cabal issue for this atm.

**Comment by RyanGlScott** [comment]
This has been addressed by the various overhauls of `lens`'s `Setup.hs` script.
