### ISSUE TITLE
Why is there no AGetter?

### ISSUE THREAD

**Issue by neongreen** [ekmett/lens#689]
It's not a big deal, but I expected it to be there (and in fact told colleague to use it before checking and finding that it's not there).

(And there's `Getting` of course, but it's a bit less useful because if the `a` is long I have to duplicate it in the signature.)

**Comment by ekmett** [comment]
Mainly because we have functions, which perfectly characterize getters.

**Comment by neongreen** [comment]
Sure, but sometimes `AGetter` is slightly more convenient. Here's a simplified version of a real-world example I encountered:

``` haskell
f tag = ... something involving getter and blah ...
  where
    getter :: AGetter Something SomethingElse
    blah :: Blah
    (getter, blah) = case tag of
      T1 -> (smth1, ...)
      T2 -> (smth2, ...)
      T3 -> (smth3, ...)
```

(Where `smth1`, `smth2` and `smth3` are autogenerated lenses for a record. The type signatures had to be added (in the real-world example) to aid the typechecker.)

With `AGetter`, everything just works. Without `AGetter`, one either has to think about how to restructure the code, or add a `to` and three `view`s. 

I'm not saying it's a big deal! Obviously it's not. What I'm saying is that 

* I expected it to be there for consistency
* there's at least one case “in the wild” where – if it existed – it would've actually gotten used

Whether it makes it worth including or not, I have no idea. Maybe not.

**Comment by neongreen** [comment]
> I expected it to be there for consistency

Today I tried to use `AGetter` again, got “not in scope”, searched and found the same issue :) Maybe just a quirk of my brain, though

**Comment by ekmett** [comment]
```haskell
f tag = ... something involving getter and blah ...
  where
    getter :: Something -> SomethingElse
    blah :: Blah
    (getter, blah) = case tag of
      T1 -> (view smth1, ...)
      T2 -> (view smth2, ...)
      T3 -> (view smth3, ...)
```

Keep in mind `AGetter` wouldn't work with `views` or any of the more general combinators other than `view`.

**Comment by neongreen** [comment]
The reason I want `AGetter` is that once I've bought into the lens ecosystem, I don't want to use functions, I want to use getters :) This said, we've already spent more time discussing this issue than I have spent working around it, so I guess I'll just close it.

**Comment by phadej** [comment]
@neongreen I tried to open up this a bit: http://oleg.fi/gists/posts/2017-03-13-why-there-is-no-agetter.html

**Comment by neongreen** [comment]
@phadej 

> Yet, we still need to clone the AGetter when the viewed type is changed

Okay, this part is what I was missing – I realized that `views` can't be used on `AGetter`, but didn't realize that I wouldn't be able to adequately use `AGetter`s in `.` pipelines.

**Comment by phadej** [comment]
@neongreen good it's now clear(er)!
