### ISSUE TITLE
hlint tests run for a long time when built against haskell-src-exts-1.19.0

### ISSUE THREAD

**Issue by RyanGlScott** [ekmett/lens#693]
I've noticed that recent Travis builds are running forever, apparently due to the `hlint` tests. [Here's](https://travis-ci.org/ekmett/lens/jobs/179423776#L1087) an example of it in action.

I reproduced this problem locally on my machine. `haskell-src-exts-1.19.0` seems to play a role in this, since `hlint-1.9.38` built against `haskell-src-exts-1.18.2` worked fine, but `hlint-1.9.38` built against `haskell-src-exts-1.19.0` stalls.

cc'ing @mpickering in case he knows what might be happening here.

**Comment by RyanGlScott** [comment]
It turns out that the title of this ticket is a bit hyperbolic. That is, the `hlint` tests aren't running _forever_, but they sure are taking longer than before. Here's the timing I get on my machine with `haskell-src-exts-1.18.2`:

```
$ time ./dist/build/hlint/hlint
real    0m1.771s
user    0m4.872s
sys     0m0.936s
```

And with `haskell-src-exts-1.19.0`:

```
$ time ./dist/build/hlint/hlint
real    0m35.408s
user    1m40.216s
sys     0m28.264s
```

I don't know why Travis is taking so much longer. Nonetheless, that's a noticeable performance regression.

**Comment by RyanGlScott** [comment]
@mpickering: I suspect that commit https://github.com/haskell-suite/haskell-src-exts/commit/a388dde3a223219a9e911bdb2edf9d8cce054bdb might have something to do with it. I tried reverting that commit and rebuilding `lens` against that version of `haskell-src-exts`, and it brought the `hlint` test time back to the previous levels:

```
$ time ./dist/build/hlint/hlint
real    0m1.728s
user    0m4.792s
sys     0m0.964s
```

**Comment by glguy** [comment]
Adding strictness to fields without also ensuring that all the uses of that constructor are strict can actually introduce additional problems with laziness due to application of a constructor with strict fields creating a thunk itself (where applications of constructors without them will not)

Also this discussion might be more appropriate on the haskell-src-exts issue tracker?

**Comment by RyanGlScott** [comment]
@glguy: Very well, I'll close this in favor of https://github.com/haskell-suite/haskell-src-exts/issues/340.

**Comment by RyanGlScott** [comment]
`haskell-src-exts-1.19.1` has been released, which reverted the problematic commit. Thanks, @mpickering!
