### ISSUE TITLE
Where is the `CreateInstance` flag?

### ISSUE THREAD

**Issue by alexanderkjeldaas** [ekmett/lens#704]
I *think* I need this flag, and this flag existed, so I wonder where it is, and why it's gone.

My use case is that I'm using GHCJS with React.  React *can* optimize re-rendering of the virtual DOM based on structural sharing of the `props` javascript object.  Components that have this behavior are derived from `PureComponent`.

So what I want to do is to have data types in Haskell (GHCJS) that are backed by a `JSVal` and use lenses to access this data as if it was normal haskell data.

So I want the `HasFoo` class to be generated, but I'd like to write my

```
instance HasFoo Foo where foo = jsValLensThing
```

on my own.

For bonus points, not having to write the above, and being able to specify the lens to use would be even more compact, since the lens would have the same name for all instances.

**Comment by RyanGlScott** [comment]
I'm not really sure what you're asking for here. Can't you just do this?

```haskell
data Foo

class HasFoo t where
    foo :: Lens' t Foo

instance HasFoo Foo where foo = jsValLensThing
```

**Comment by alexanderkjeldaas** [comment]
I'm refering to the example that is used in the lens documentation:

```
data Foo = Foo { _fooX, _fooY :: Int }
$(makeClassy ''Foo)

```

now I can't write 

```
instance HasFoo Foo where
    foo = jsValLensThing
```

**Comment by glguy** [comment]
Can you write a working example of what you'd expect things to look like. I'm struggling to guess what `jsValLensThing :: Prism' Foo Foo` might be
