### ISSUE TITLE
Overloaded field accessors together with DuplicateRecordFields: Support for unprefixed field names

### ISSUE THREAD

**Issue by mtesseract** [ekmett/lens#705]
Hi,

unless I am overlooking something, there is currently no support for generating overloaded field accessors (like with makeFields) but without the need to prefix each field name with the type name.

Using GHC's DuplicateRecordFields extension we can now define record types like

    (1) data Foo = Foo { _name :: String }
        data Bar = Bar { _name :: String }

instead of 

    (2) data Foo = Foo { _fooName :: String }
        data Bar = Bar { _barName :: String }.

But ```makeFields``` expects the definitions in the form (2) in order to generate acessors named ```name```. It would be nice to also have support in lens for generating accessors named ```name``` from the definitions (1).

Thanks,
Moritz

**Comment by glguy** [comment]
I believe you can use a custom naming rule and `makeLensesWith`

**Comment by ekmett** [comment]
We could definitely add a flag or just add a custom naming rule to allow this. Allowing it by default could be a bit problematic due to the fact that it would change an existing behavior and make some extra lenses you don't expect.

**Comment by mtesseract** [comment]
See PR #706

**Comment by ekmett** [comment]
Merged.

**Comment by mtesseract** [comment]
Cool, thank you. :-)

**Comment by ekmett** [comment]
Now you get to enjoy the interminable delay while we hem and haw about when the next release will be. ;)
