### ISSUE TITLE
Cut GHC 8.2-compatible releases of lens and dependencies

### ISSUE THREAD

**Issue by RyanGlScott** [ekmett/lens#709]
This is really a meta-issue, as it affects many packages besides `lens`. I figured this is as good of a place as any to file this issue.

To prepare for a GHC 8.2-compatible release, we need to overhaul quite a few `Setup.hs` scripts used in `lens` and its dependencies (and other packages in the `lens` ecosystem). That's because the current code has fallen out-of-sync with the `Cabal` API as of `Cabal-1.25`, which means if you try to configure one of these packages with GHC 8.2, you'll get an error like [this one](https://github.com/haskell/cabal/issues/4157#issue-193858754).

To help alleviate these growing pains in the future, we should go through and update these `Setup.hs` scripts (and the `doctests.hs` testsuite drivers) to use @phadej's new `cabal-doctest`-based harness (see his [`distributive` patch](https://github.com/ekmett/distributive/pull/27) for an example). This is backwards-compatible back to GHC 7.0 and has been tested on a pretty wide variety of configurations (`cabal new-build`, `cabal` sandboxes, `stack`, packages with `c-sources`, etc.). And most importantly, this will let us apply future `Setup.hs` bugfixes in a single location, the `cabal-doctest` library, saving us some headaches down the road whenever the `Cabal` API changes later.

Toward this end, here are all of the actively maintained Hackage packages that I can think of whose `Setup.hs` scripts will need to be updated:

* [x] `ad` ([commit](https://github.com/phadej/ad/commit/cc5619f8a3f6bd1045e2862d72d88659ed23f8d0)) ([Hackage](http://hackage.haskell.org/package/ad-4.3.3))
* [x] `approximate` ([commit](https://github.com/ekmett/approximate/commit/fada98729ce8712a76d6cd205b61eff3ba3adaf9)) ([Hackage](http://hackage.haskell.org/package/approximate-0.3))
* [x] `bits` ([commit](https://github.com/ekmett/bits/commit/415324c782b2a374d1b84503d18f8cca5678049b)) ([Hackage](http://hackage.haskell.org/package/bits-0.5.1))
* [x] `bound` ([commit](https://github.com/ekmett/bound/commit/d66d98f4f1ca09e43e81a8d040fb1ceba0ca30ec)) ([Hackage](http://hackage.haskell.org/package/bound-2))
* [x] `bytes` ([commit](https://github.com/ekmett/bytes/commit/2af110fd3b9f9d6ae9ae0227775472235430ddd8)) ([Hackage](http://hackage.haskell.org/package/bytes-0.15.3))
* [X] `comonad` ([commit](https://github.com/ekmett/comonad/commit/7aa45018f51811f0222127c74818260f5f7722e0)) ([Hackage](http://hackage.haskell.org/package/comonad-5.0.1))
* [x] `compensated` ([commit](https://github.com/ekmett/compensated/commit/5225e5e34583c6ab95ca8c49125f1e006258a57e)) ([Hackage](http://hackage.haskell.org/package/compensated-0.7.1))
* [X] `distributive` ([commit](https://github.com/ekmett/distributive/commit/65f63b1456134d3a67e895a2e23dc7746a86a7a4)) ([Hackage](http://hackage.haskell.org/package/distributive-0.5.2))
* [x] `ersatz` ([commit](https://github.com/phadej/ersatz/commit/d038bef7ed896ef46cf0525b1d0440be41b085ab)) ([Hackage](http://hackage.haskell.org/package/ersatz-0.4))
* [x] `folds` ([commit](https://github.com/ekmett/folds/commit/16942a8431189db6aa1d46982bfd57591da0505d)) ([Hackage](http://hackage.haskell.org/package/folds-0.7.3))
* [x] `gc` ([commit](https://github.com/ekmett/gc/commit/4f34411094bd92c5367dfc5fa4954f053acda292)) ([Hackage](http://hackage.haskell.org/package/gc-0.0.1))
* [x] ~`gl` (commit) (Hackage)~
* [x] `heaps` ([commit](https://github.com/ekmett/heaps/commit/f3f8b59099d27fa77b978275d427de9869fbdde1)) ([Hackage](http://hackage.haskell.org/package/heaps-0.3.4.1))
* [x] `hyperloglog` ([commit](https://github.com/ekmett/hyperloglog/commit/8ac4e58e51c0341f569307d678e33a0f9547bc76)) ([Hackage](http://hackage.haskell.org/package/hyperloglog-0.4.1))
* [x] `hyphenation` ([commit](https://github.com/ekmett/hyphenation/commit/f1de338693f0ca9d3e9a0853e4363167ab92915e)) ([Hackage](http://hackage.haskell.org/package/hyphenation-0.7))
* [x] `intervals` ([commit](https://github.com/ekmett/intervals/commit/e8efe284f124e73b8d463c230dc904644f977cd6)) ([Hackage](http://hackage.haskell.org/package/intervals-0.8))
* [x] `lens` ([commit](https://github.com/ekmett/lens/commit/b42d114b173fecf082e25240eabfd7eb5301fbdf)) ([Hackage](http://hackage.haskell.org/package/lens-4.15.2))
* [x] `lens-action` ([commit](https://github.com/phadej/lens-action/commit/66e40e5fbc2a53747ff2eab9c5ebc56c0fef3db9)) ([Hackage](http://hackage.haskell.org/package/lens-action-0.2.1))
* [x] `lens-aeson` ([commit](https://github.com/lens/lens-aeson/commit/34e3f71e7ce87eccba024db3f70d4ac2e9894fa0)) ([Hackage](http://hackage.haskell.org/package/lens-aeson-1.0.1))
* [x] `log-domain` ([commit](https://github.com/ekmett/log-domain/commit/4fb445876e634d7d78e5904bf56afa06d3a5d018)) ([Hackage](http://hackage.haskell.org/package/log-domain-0.11.1))
* [x] `linear` ([commit](https://github.com/ekmett/linear/commit/1f0cbeaac161cb140303c91fb3b05845813b4368)) ([Hackage](http://hackage.haskell.org/package/linear-1.20.6))
* [ ] `linear-accelerate` ([commit](https://github.com/ekmett/linear-accelerate/pull/6)) (Hackage)
* [x] `machines` ([commit](https://github.com/ekmett/machines/commit/6f34c32e33e70e745ddf5704fdead68a7733c864)) ([Hackage](http://hackage.haskell.org/package/machines-0.6.2))
* [x] `parsers` ([commit](https://github.com/phadej/parsers/commit/5dd9522ca3bf6613e95951b3cdcb7123def59688)) ([Hackage](http://hackage.haskell.org/package/parsers-0.12.5))
* [x] `rcu` ([commit](https://github.com/ekmett/rcu/commit/a08e0b6ed40709052bd84d9b0d2bbd5583c9ae1b)) ([Hackage](http://hackage.haskell.org/package/rcu-0.2))
* [X] `semigroupoids` ([commit](https://github.com/ekmett/semigroupoids/commit/1a2c2bbfd5b1fa303abdd128d4ec95c48c6ed26b)) ([Hackage](http://hackage.haskell.org/package/semigroupoids-5.2))
* [x] `structs` ([commit](https://github.com/ekmett/structs/commit/f4f5d5516e644d2faf541a4c6a5f6935655cf586)) ([Hackage](http://hackage.haskell.org/package/structs-0.1))
* [x] `trifecta` ([commit](https://github.com/ekmett/trifecta/commit/62111bc203a81bbe3194f7a89325079313586bea)) ([Hackage](http://hackage.haskell.org/package/trifecta-1.7))
* [x] ~`wl-pprint-terminfo` (commit) (Hackage)~
* [x] `zippers` ([commit](https://github.com/ekmett/zippers/commit/ed42a18d3199a91365e1a57444a8894829b2d4a1)) ([Hackage](http://hackage.haskell.org/package/zippers-0.2.3))

Other issues:

* [X] `bifunctors` needs a new release due to https://github.com/ekmett/bifunctors/pull/55 ([Hackage](http://hackage.haskell.org/package/bifunctors-5.4.2))

**Comment by RyanGlScott** [comment]
It turns out that there are two minor bugs we'll have to watch out for:

* https://github.com/haskell/cabal/issues/4288. The workaround is to depend on `Cabal` explicitly in `setup-depends`.
* https://github.com/commercialhaskell/stack/issues/2976. The workaround is to depend on `directory` and `filepath` explicitly in `setup-depends`.

**Comment by phadej** [comment]
I'll update `bound`, `intervals` has a PR. Could do PR for the rest too if you don't mind @RyanGlScott ?

**Comment by phadej** [comment]
@RyanGlScott  Btw, in your commits you copy pasted `distributive` into changelogs.

**Comment by RyanGlScott** [comment]
@phadej, if you don't mind making 16 different PRs, then go for it :)

I noticed that copy-paste bug about 4 commits in... I should have fixed that in subsequent commits, however.

**Comment by phadej** [comment]
@RyanGlScott, I don't mind, will do on Monday

**Comment by phadej** [comment]
`rcu` and `compensated` aren't GHC-8.0 compatible, will omit them for now.

**Comment by phadej** [comment]
`wl-pprint-terminfo` doesn't have doctests

**Comment by phadej** [comment]
`ersatz` has the harness, but not a single doctest comment.

**Comment by phadej** [comment]
heaps repository has 0.3.2.1, when the released one is 0.3.3. Did @ekmett forgot to push?

**Comment by phadej** [comment]
Kind of related, the `free-5` major bump. I made an issue for kan-extensions: https://github.com/ekmett/kan-extensions/issues/34

There's also `keys`, `lens`, `adjunction` and `ad` with restrictive `free < 5`, bound, but it seems that there the changes aren't breaking anything. 

Also there is no `prelude-extras` anywhere (in `master`s)

**Comment by RyanGlScott** [comment]
@phadej, good catches. Maybe we should have a PR to simply remove `Setup.hs` scripts from `ersatz` and `linear-accelerate` if they don't actually use them for anything?

Bumping the `free` upper version bounds sounds like a good idea.

I'm not sure I understand your comment about `prelude-extras`?

**Comment by phadej** [comment]
`prelude-extras`: what to do with it, it's not needed in "kmettverse", should it also be deprecated (in favour of transformers-0.5 / base-4.9)

**Comment by phadej** [comment]
@RyanGlScott let's indeed remove Custom setup from them, it's easy to add back if we want to add doctests later.

I'll follow-up on `free` + `kan-extensions` changes during this week.

I did a test-build with `8.1.20170123`, everything seems to compile. In later version I did broke `reflection` and `constraints`, so someone have to fix them too (`Integer` -> `Natural`, https://phabricator.haskell.org/D3024).

Now waiting for `--enable-tests` build to complete (or fail), so far so good (https://github.com/phadej/kmettverse/tree/ghc-8.2, though with some local modifications, and some submodules pointing to commits not in ekmett's repositories)

**Comment by RyanGlScott** [comment]
I've made a lot of progress on releasing new versions of these libraries to Hackage, but there's still a handful of packages that I haven't dealt with yet for various reasons. I'll categorize them below:

* Packages which directly (or indirectly) depend on `quickcheck-instances`, which doesn't support GHC 8.2 yet:
  * `parsers`
  * `trifecta` (depends on `parsers`)
* Packages which depend on `accelerate`, which doesn't support GHC 8.2 yet:
  * `linear-accelerate`
* Packages which depend on `safecopy`, which doesn't support GHC 8.2 yet (note that upgrading `safecopy` would require a 8.2-compatible `quickcheck-instances`):
  * `approximate`
  * `compensated`
  * `hyperloglog`
  * `log-domain`
* Packages which don't compile with GHC 8.2 due to [Trac #13622](https://ghc.haskell.org/trac/ghc/ticket/13622):
  * `ersatz`
* Packages which I'm holding off on until https://github.com/phadej/cabal-doctest/issues/9 is resolved:
  * `structs`
* Miscellaneous
  * `bound`: I'm not sure if all the changes that @phadej hinted at in https://github.com/ekmett/bound/issues/32 have landed yet.

**Comment by ekmett** [comment]
@phadej: re heaps, looks like, pushed up what was in my local repo after a quick merge.

**Comment by cartazio** [comment]
Did bound get a release yet? @phadej?

**Comment by phadej** [comment]
@cartazio no. It's not 8.2 ready yet.

**Comment by cartazio** [comment]
Was there ever an 8.0.2 friendly release ?

**Comment by phadej** [comment]
@cartazio unfortunately no. I have used tip of the `master` in my own developments.

**Comment by RyanGlScott** [comment]
Good news: almost everything has been updated for GHC 8.2! At this point, the only library on this list that hasn't been covered yet is `linear-accelerate`, for which I've opened [its own issue](https://github.com/ekmett/linear-accelerate/issues/8), so I'll close this one.
