### ISSUE TITLE
Un-generalize 'both'?

### ISSUE THREAD

**Issue by neongreen** [ekmett/lens#714]
At work I had a situation where `both` was used on 2-tuple, and then that 2-tuple was changed to a 4-tuple; `both` kept working, but only on the last two elements of the tuple, which led to a bug in the logic.

I understand why `both` does what it does (and I understand that in reality the same kind of complaint applies whenever `Foldable/Traversable` and tuples collide), but I'd still be in favor of un-generalizing `both`.

(Also, if we un-generalize it we'll lose the ability to use it on `Either`, but we can just tell people to use `chosen`.)

**Comment by phadej** [comment]
Counter-question: why you use 4-tuple, and not a data type like [`V4`](https://www.stackage.org/haddock/lts-8.5/linear-1.20.5/Linear-V4.html#t:V4), or more domain specific (especially if sometimes it's not homogenous)?

I.e. is the problem in the `both` being general, or that *your* type isn't specific enough?

In the same way we can
> just tell people to use `chosen`
we can tell you
> to just use your own specialized `both`

I'm :-1:. I don't use `both` in the professional code, but it's handy in  examples as defined now.

**Comment by neongreen** [comment]
> we can tell you
> to just use your own specialized `both`

This is exactly what we did with `Foldable` (just threw it away) and what we're going to do with `both` (make a HLint rule which suggests using `each` instead). So, *my* problem is already solved.

> Counter-question: why you use 4-tuple, and not a data type like V4

Sure, I agree that the problem would've also been avoided if we didn't use a 4-tuple. However, I would vehemently disagree with the view (no idea whether you actually hold it or not) that once someone uses a less optimal solution than they could've, they suddenly become 100% responsible for shooting themselves in the foot.

The reason I've raised this issue is that I think `both` is a bad tradeoff between “being as general as possible” and “protecting people from shooting themselves in the foot”; the reason I think this is a bad tradeoff is that I haven't seen `both` actually used for anything other than 2-tuples and `Either`, and so it feels to me that the cost of the generality loss would be negligible. I'll be happy to hear that I'm wrong and – for instance – `both` actually has lots of other uses which justify the tradeoff.

**Comment by ekmett** [comment]
I'm personally rather :-1: on this suggestion. It'd break a fair bit of my own code. (I personally use `both` to walk all sorts of things with two type parameters, such as syntax trees with both type and term variables.) Lens combinators tend to be designed to be as general a possible, and this would violate that tenet, forcing us to come up with another useless name to walk `both` sides of an `Either` and/or for the more powerful `bitraverse f f` Traversal. The less general version is packaged up by all of the alternative lens libraries, but they all err on the side of simplicity vs. generality.

Read `both` as walking the last two type parameters. If you really want to walk over all the parts of a 4-tuple instead use `each`, but then refactoring the type leads to even more drastic divergence in behavior as your tuple type changes to something else.

**Comment by neongreen** [comment]
> (I personally use both to walk all sorts of things with two type parameters, such as syntax trees with both type and term variables.) 

Okay, good to know!

> Lens combinators tend to be designed to be as general a possible, and this would violate that tenet

Sure, this makes sense too.
