### ISSUE TITLE
Replacer?

### ISSUE THREAD

**Issue by pthariensflame** [ekmett/lens#72]
`Setter`s are capable of replacing the target value(s) because they are capable of modifying the target value(s).  Modification always allows replacement as a special case (via `const` and its ilk), but you cannot generate modification from solely replacement (if you have both replacement and retrieval, you can, but then you just end up with a `Traversal`).

This seems to hint at a supertype of `Setter`:  `Replacer` (plus `Indexed` and/or `Simple` variants, of course).  Essentially:
- `Getter a c` is isomorphic to `a -> c`
- `Setter a b c d` is isomorphic to `(c -> d) -> a -> b`
- `Replacer a b d` is isomorphic to `d -> a -> b`

I've come up with a couple of encodings for `Replacer` that try to fit within the van Laarhoven model, and I'd like to generate some discussion of this.  It's not critical to me, but it _is_ an interesting hole in the current design space.
- `type Replacer a b d = forall f. (Settable f) => (forall c. c -> f d) -> a -> f b`
- `type Replacer a b d = forall f. (Settable f) => (Void -> f d) -> a -> f b`

**Comment by Lev135** [comment]
For those, who will read this like me. For setting-only operation you can just use `Setter s t () b` (it's actually isomorphic to `b -> s -> t`, though definitions of `Replacer` above are not -- we should use unit type instead of `Void`). So
```hs
type Replacer s t b  = Setter s t () b

replacer :: (b -> s -> t) -> Replacer s t b
replacer h fb = setting (h . ($ ())) fb

-- and standard 'set' operation works fine with it
```

**Comment by ekmett** [comment]
You can write that down, but it doesn't compose or comply with the laws presented in the original [Mirrored Lenses](http://comonad.com/reader/2012/mirrored-lenses/) post. Ultimately, the `a` and the `b` should be related by the same substitution that relate `s` and `t`, in your Replacer, they are unrelated.

The lens library doesn't preclude you from using such a beast, but it is not a lawful optic, and you have to reason case-by-case, combinator-by-combinator, to see if it does what you want as you go.

Your mileage may vary. Caveat emptor. Here be dragons, etc.
