### ISSUE TITLE
Use coersion in Getter

### ISSUE THREAD

**Issue by nponeccop** [ekmett/lens#726]
There is seemingly impossible `magicCoerse` function that can be used to simplify the implementations of two functions in `Control.Lens.Getter`:

```hs
magicCoerce :: (Functor f, Contravariant f) => f a -> f b
magicCoerce = contramap (const ()) . fmap (const ())

to :: (Profunctor p, Contravariant f, Functor f) => (s -> a) -> Optic'   p f s a
to k = dimap k magicCoerce

ito :: (Indexable i p, Contravariant f, Functor f) => (s -> (i, a)) ->   Over' p f s a
ito k = dimap k magicCoerce . uncurry . indexed
```

The reason why this function exists is that the only functor that is both covariant and contravariant is the `Const` functor. And for `Const` functor the same "coersion" exists because the type parameter is phantom and is not used at runtime:

```hs
constCoerce :: Const a b -> Const a c
constCoerce a = Const $ getConst a
```

Also `to` has a more general type now, so `ito` can be rewritten as:

```hs
ito k = to k . uncurry . indexed
```

Finally, `magicCoerce` is semantically equivalent to `unsafeCoerce` which may be faster.

What do you think?

**Comment by phadej** [comment]
`magicCoerce` is called [`phantom`](http://hackage.haskell.org/package/contravariant-1.4/docs/Data-Functor-Contravariant.html#v:phantom)

I'm not sure your variant is simpler than the current

```haskell
to k = dimap k (contramap k)
```

when instantiated to `p = (->)` and `f = Const` (i.e. in `view`), your and current variant will be compiled to `k . coerce` anyway. But current will use less GHC power. I don't see real benefit

---

> Also to has a more general type now, 

Does it?

**Comment by nponeccop** [comment]
> `magicCoerce` is called `phantom`

ahh.. I was looking for it in `Data.Functor.Const`. I didn't think it was in `contravariant`.

> I'm not sure your variant is simpler than the current

The current variants of

```hs
to k = dimap k (contramap k)
ito k = dimap k (contramap (snd . k)) . uncurry . indexed
```
Seem IMHO somewhat more convoluted and harder to understand than

```hs
to k = dimap k phantom
ito k = dimap k phantom . uncurry . indexed
```
as extra `k` and `snd . k` are essentially irrelevant.

It doesn't matter within the library, but it may be worth to mention in the documentation. Also documentation of `phantom` describes what is achieved by having both `Functor` and `Contravariant` constraints pretty well.

For example the docs say that `contramap x = phantom` for any `x`, so the abovementioned `k` and `snd . k` arguments only supply their type.

> But current will use less GHC power

What do you mean?

**Comment by ekmett** [comment]
Using contramap here is both cheaper than doing both contramapping and fmapping, and ever so slightly more permissive. We used to do it the way you propose. We consciously switched to the current approach. Well, technically, we used the dual approach, as you can use absurd if you flip the fmap and contramap, and then it is 100% clear the type parameter can't be used.

**Comment by ekmett** [comment]
Looks like @glguy snuck it in when I wasn't looking. I'm actually going to remove the constraint because I actually found it somewhat informative to play with these with mere contravariant functors.

**Comment by ekmett** [comment]
Bah. "Fixing" this means triggering `-fno-warn-redundant-constraints` all over hell and back. This "helpful" warning ensures we can't have nice things. Screw it.

**Comment by ekmett** [comment]
7d16b2b871 offers the more permissive types possible under the current approach.

**Comment by phadej** [comment]
@ekmett removing the `Functor` constraint from `to` will trigger `-fwarn-redundant-constraints` warnings in the user code, not only inside `lens`

```haskell
type Getter s a = forall f. (Contravariant f, Functor f) => (a -> f a) -> s -> f s

foo :: Getter Bar Foo
foo = to _foo
```

should the `Functor` be removed from `Getter` as well?

**Comment by ekmett** [comment]
Only on 8.0.1, in 8.0.2+ --fwarn-redundant-constraints is not considered part of -Wall.

**Comment by ekmett** [comment]
Given that situation I'm comfortable telling folks on 8.0.1 to upgrade or accept that it emits useless warnings in many situations.
