### ISSUE TITLE
maximum1Of and minimum1Of

### ISSUE THREAD

**Issue by Icelandjack** [ekmett/lens#727]
Since we have `firstOf1`, `lastOf1` (why are they not called `head1Of`, `last1Of`?) it may be a good idea to give a `maximum1Of`, `minimum1Of` that do not return a `Maybe` using a `Getting` over `Data.Semigroup.Max`, `Data.Semigroup.Min`.

I don't have *lens* atm but they should be easy enough to write.

We could also add total versions of `foldr1Of`, `foldl1Of`.

**Comment by phadej** [comment]
I actually think to rename them to `first1Of`; I agree that `1` should be before `Of`. `first` because we already have `firstOf`.

I'll add do the name change and add `maximum1Of` and `minimum1Of`, as well as `traverse1Of`. I @ekmett doesn't object.

**Comment by Icelandjack** [comment]
My preference comes from [yak shaved names for `Data.Semigroup.Foldable`](https://github.com/ekmett/semigroupoids/issues/49), appending `1` appeals to me because of the consistency

```haskell
fold1    :: (Foldable1 f, Semigroup m) => f m -> m
foldMap1 :: (Foldable1 f, Semigroup m) => (a -> m) -> (f a -> m)

head1    :: Foldable1 f          => f a -> a
last1    :: Foldable1 f          => f a -> a
minimum1 :: (Ord a, Foldable1 f) => f a -> a
maximum1 :: (Ord a, Foldable1 f) => f a -> a
```
(`foldr1`, `foldl1` adhere to this already in a way) 

food for thought

> I'll add do the name change and add maximum1Of and minimum1Of, as well as traverse1Of. I @ekmett doesn't object.

Sounds good

**Comment by Icelandjack** [comment]
> `first` because we already have `firstOf`.

Yeah, a bit unfortunate since it takes after (a safe version of) `head` but is not called `headOf`.

**Comment by phadej** [comment]
I'll add a notes 

> *Note:* `firstOf` is what you are looking for, if you are searching for `headOf`.

Maybe Google will be smart enough eventually and help people, if we help it.

**Comment by Icelandjack** [comment]
Yeah that's good
