### ISSUE TITLE
Stack warning when installing lens

### ISSUE THREAD

**Issue by crockeea** [ekmett/lens#731]
When using stack to install lens, I get the following warning:
```
Package lens uses a custom Cabal build, but does not use a custom-setup stanza
Not using the explicit setup deps approach based on configuration
Strongly recommend fixing the package's cabal file
```
My stack version is `Version 1.4.0, Git revision e714f1dd3fade19496d91bd6a017e435a96a6bcd (4640 commits) x86_64 hpack-0.17.0`.

**Comment by ekmett** [comment]
This isn't currently fixable without shutting off users of older versions of cabal.

**Comment by ekmett** [comment]
This isn't currently fixable without shutting off builds for users of older versions of cabal.

**Comment by ekmett** [comment]
You're going to be seeing this unfortunate warning on a lot of my packages for the next couple of years.

**Comment by phadej** [comment]
In the next version there will be `custom-setup` stanza, with `setup-depends`, so it will ago (already fixed in `master`)

**Comment by ekmett** [comment]
What is the oldest version of ghc that ships with a cabal that supports custom-setup stanzas?

**Comment by phadej** [comment]
@ekmett 8.0.x, yet the older `Cabal` don't care about `custom-setup` stanzas, they just issue a non-fatal warning (something like "unrecognized stanza"). The similar mechanism let us add `benchmark` stanzas back then; older `Cabal`s just didn't care about it.

**Comment by ekmett** [comment]
Speaking of `cabal-doctest`. Is there an issue with it on 8.2.1?

https://travis-ci.org/ekmett/lens/jobs/227982077#L435

**Comment by phadej** [comment]
@ekmett yes, I'm waiting for `Cabal` API to stabilize before I'll fix it. The official tag should be done soon, and there *are* changes not yet in `hvr-ppa` version of GHC (e.g. revert of `rewriteFile` breakage).

I'm not willing to release a version supporting a version which will be never released.

The related ticket in `Cabal`: https://github.com/haskell/cabal/issues/3576#issuecomment-298592834

**Comment by RyanGlScott** [comment]
As @phadej noted, you won't get this warning on a sufficiently recent Stackage resolver (e.g., `nightly-2017-06-11`, which I tested), since it contains a `lens` with a `custom-setup` stanza.

We've done our part here, so I'll close this.
