### ISSUE TITLE
Generate lenses for data families

### ISSUE THREAD

**Issue by neongreen** [ekmett/lens#733]
Currently it's impossible to invoke `makeLenses` on a data family. I'd make a pull request, but I'm not sure how such an invocation could even look like:

* if `DF` is a data family with a single parameter a simple `makeLensesData 'DF 'Foo` suffices
* if `DF` is a data family with several parameters, we need a list: `makeLensesData 'DF ['Foo, 'Bar]`
* if parameters can be non-simple (`DF (Maybe Foo) (Maybe Bar)`), we'd have to use something like `makeLensesData [t|DF (Maybe Foo) (Maybe Bar)|]`

Have you got any ideas for better solutions? `declareLenses` could work, but only for standalone instances and not for associated data families.

**Comment by glguy** [comment]
The value constructor provides a unique name suitable for reification.

**Comment by RyanGlScott** [comment]
The way I handle data family instances in `bifunctors` is to allow users to specify the name of a constructor:

```haskell
data family Foo a b c
data family instance Foo Int b c = FooInt
data family instance Foo Char b c = FooChar1 | FooChar2

$(deriveBifunctor 'FooChar1) -- or, equivalently, $(deriveBifunctor 'FooChar2)
```

It's a tad strange to look at, but it gets the job done, and given the current technology we have in Template Haskell, I think it's about as concise as you can get.

**Comment by RyanGlScott** [comment]
See [here](https://github.com/ekmett/bifunctors/blob/d7a9cf516addac543059224ea7d335f032a14026/src/Data/Bifunctor/TH.hs#L466) for the code which dispatches on a `Name` to see if it's a vanilla datatype name or a data family instance constructor name, and retrieves the appropriate metadata.

**Comment by neongreen** [comment]
@glguy huh, right, I forgot about it. Okay, then should `makeLenses` be modified, or should `makeLensesData` or some new function be introduced instead?

**Comment by glguy** [comment]
The solution is going to be to modify [reifyDatatype](http://hackage.haskell.org/package/th-abstraction-0.1.0.0/docs/Language-Haskell-TH-Datatype.html#v:reifyDatatype) , which I'm switching lens' Template Haskell code to use at this moment.

**Comment by RyanGlScott** [comment]
Ooh, I didn't know about `th-abstraction`. That looks quite useful for sharing a lot of this unsightly Template Haskell plumbing among libraries!

**Comment by glguy** [comment]
Transition to th-abstraction complete 1aa37c4f628d9813ce6b5abcc82a4aed4a43e2af

Next step is to add the clever data instance logic to reifyDatatype.

**Comment by glguy** [comment]
Progress continues ff6d67daa417a1d67e85a8b87e71f2dc58c2f2b0
