### ISSUE TITLE
Compile-failure: Module `GHC.Exts' does not export `Int32'

### ISSUE THREAD

**Issue by hvr** [ekmett/lens#735]
I just ran into the followin compile error on a 32-bit arch (AIX/PPC):

```
[37 of 80] Compiling Control.Lens.Wrapped ( src/Control/Lens/Wrapped.hs, dist/build/Control/Lens/Wrapped.o )

src/Control/Lens/Wrapped.hs:175:28: error:
    Module `GHC.Exts' does not export `Int32'
    |
175 | import           GHC.Exts (HTYPE_TIMER_T)
    |                            ^^^^^
cabal: Failed to build lens-4.15.2 
```

Curiously, on Linux, `timer_t` results in

```c
#define HTYPE_TIMER_T Ptr ()
```

while on other archs, this may be defined as e.g.

```c
#define HTYPE_TIMER_T Int32
```

being defined.

Fwiw, that kind of masterful usage of CPP looks quite scary to me...  as this relies on the accidental syntactical compatiblity of a type `Ptr ()` being coincidentally compatible with the import specification `Ptr ()`, where `()` in the former denotes the unit-type, and in the latter denotes the empty list of constructors... genius! ;-)

**Comment by hvr** [comment]
By consulting the Git history I found the commit f4eb9fb11fc5ae01e2cf531b6922250ee20bb5af which where @RyanGlScott introduced this.

**Comment by RyanGlScott** [comment]
I was afraid some OS out there would break this... thanks for confirming.

I've committed 7d2585113e2efebf221433e36ec88ebea07b88c4, which I believe should address this issue and make the code much cleaner. Can you confirm that `lens` HEAD builds for you now?

**Comment by glguy** [comment]
It appears that HTYPE_TIMER_T can be: `Word_` `Int_`, `Float`, `Double`, `LDouble`, `Ptr ()`, or `NotReallyAType`

Also, what's an `LDouble`? Do we have such a type??

**Comment by RyanGlScott** [comment]
Apparently, GHC has [some unused functionality](http://git.haskell.org/ghc.git/blob/5179fd4d71ae67bfb34cedf1e1d4f3b3de8e974d:/libraries/base/aclocal.m4#l157) for detecting if a C floating-point type is equal to `long double`. The [comments](http://git.haskell.org/ghc.git/blob/5179fd4d71ae67bfb34cedf1e1d4f3b3de8e974d:/libraries/base/Foreign/C/Types.hs#l175) in `Foreign.C.Types` even say:

```haskell
-- GHC doesn't support CLDouble yet
-- "realToFrac/a->CLDouble"  realToFrac = \x -> CLDouble (realToFrac x)
-- "realToFrac/CLDouble->a"  realToFrac = \(CLDouble x) -> realToFrac x
```

So for whatever reason, `LDouble` was relegated to the cutting room floor.

**Comment by hvr** [comment]
@RyanGlScott `lens` HEAD builds on ppc/aix for me now!
