### ISSUE TITLE
Travis builds are timing out

### ISSUE THREAD

**Issue by RyanGlScott** [ekmett/lens#738]
The `lens` test suites take longer than you'd expect on Travis CI's build machines, sometimes going for periods of longer than 10 minutes (Travis's timeout limit) without any output. See [here](https://travis-ci.org/ekmett/lens/jobs/241541282#L748) for an example.

We should try using [`travis_wait`](https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received) to see if that eliminates the problem.

**Comment by glguy** [comment]
Maybe we can make doctests less bad? It seems like it's doing way more work than it should be.

**Comment by RyanGlScott** [comment]
Perhaps, but I think this is to a large degree a symptom of Travis's build machines. For instance, all tests run to completion on my machine in about 3 minutes, whereas it drags on much longer on Travis.

Any tweaks to make the tests faster would also be welcome, of course.

**Comment by glguy** [comment]
To be clear I don't want to change the tests, I want to fix the doctests driver. Most of the test time is spent recompiling things

**Comment by glguy** [comment]
On my computer the tests take over 13 minutes. If I fixed doctests by removing this line linked below they take 1.5 minutes. This line appears to be a workaround for a bug in an old version of GHC.

https://github.com/sol/doctest/blob/master/src/Runner.hs#L129

**Comment by RyanGlScott** [comment]
Nice find, @glguy! Hopefully @sol is open to merging https://github.com/sol/doctest/pull/165, which implements your suggestion.

**Comment by RyanGlScott** [comment]
After talking with @glguy, there are two ideas for bringing down the time on Travis:

1. Use `cabal new-build` and `cabal.project` to vendor in [this fork of `doctests`](https://github.com/RyanGlScott/doctest/commit/72abefc9244fe4be123e541cd75540e2bafecbd2) which is substantially faster. Of course, we'd need to actually port the Travis testing infrastructure over to `cabal new-build` in the first place (see #646 for an attempt at this).
2. `apt-get install hlint` instead of installing `hlint` the library. This will avoid the need to install `haskell-src-exts` and a bunch of other dependencies.

**Comment by glguy** [comment]
I forgot that we weren't using new-build for the lens builds. We don't need to use new-build to vendor doctest
