### ISSUE TITLE
Numeric.Lens.integral doesn't catch arithmetic exceptions

### ISSUE THREAD

**Issue by treeowl** [ekmett/lens#748]
```
> (-3) ^? integral :: Maybe Natural
*** Exception: arithmetic underflow
```

I believe the `fromInteger` side should catch underflow and overflow exceptions and convert to `Nothing`. Rewrite rules for `Int`, `Word`, `IntN`, `WordN`, and `Integer` can skip that overhead.

**Comment by glguy** [comment]
integral is a lens, and wraps an API that doesn't indicate failure. I don't think catching these exceptions in pure code is appropriate.

**Comment by treeowl** [comment]
@glguy, `integral` is not a lens; it's a prism. I don't understand what you're getting at.

**Comment by treeowl** [comment]
Oh, you just mean that the underlying API is broken. I guess that's a valid criticism of the underlying API; but it leads to `integral` having pretty weird behavior for `Natural`.

**Comment by ekmett** [comment]
Ultimately, Natural is a somewhat limited beast due to the design of Num. The alternative here lets pure code distinguish bottoms, which compromises the monotonicity of pure code in Haskell with respect to the information ordering. That is far more unexpected than a function returning bottom here.

**Comment by treeowl** [comment]
We needn't compromise monotonicity, I don't think. As long as we force the
argument before installing an exception handler, we're monotonic, right?

**Comment by ekmett** [comment]
If you can do something different for something less defined (a thrown Arithoverflowexception) than you do for something more defined (everything else, including the integral and non-integral cases here) then you violate monotonicity.

Monotonicity: a <= b ==> f a <= f b

throw ArithOverflowException <= 12  but Nothing and Just 12 are incomparable. Hence monotonicity is violated.
