### ISSUE TITLE
Add minMaxOf?

### ISSUE THREAD

**Issue by neongreen** [ekmett/lens#752]
We've already got `minimumOf` and `maximumOf`; it is sometimes useful to have `minMaxOf` as well that computes both minimum and maximum in one pass (a coworker recently needed that and we ended up implementing it in our utils library).

If it's accepted, I can make a PR.

**Comment by Gurkenglas** [comment]
`flip foldl1Of' (min *** max)`, you mean?

**Comment by neongreen** [comment]
Almost (I want `minMaxOf` to return a `Maybe`, like `minimumOf` and `maximumOf` do)

**Comment by ekmett** [comment]
At that point you already have the Min and Max monoids and it is a pretty easy job to fold over things yourself. This doesn't really rise to the Fairbairn threshold for me.
