### ISSUE TITLE
Change instances generated by makeFields to avoid “Illegal type synonym family application” errors

### ISSUE THREAD

**Issue by lexi-lambda** [ekmett/lens#754]
Currently, it’s possible to make `makeFields` generate an instance which is not accepted by GHC if a record field’s type is an application of a type synonym family. For example, this code will produce an error:

```haskell
type family Fam a
data Rec a = Rec { _recFam :: Fam a }
makeFields ''Rec
```
```
• Illegal type synonym family application in instance: Fam a_an7y
• In the instance declaration for
    ‘HasFam (Rec a_an7y) (Fam a_an7y)’
```

I *think* this instance really ought to be legal due to the fundep, but GHC does not allow it. I’ve opened [GHC ticket #14046](https://ghc.haskell.org/trac/ghc/ticket/14046) to track that problem, but (as mentioned in the ticket) there is actually a workaround. Currently, `makeFields` generates an instance like this:

```haskell
instance HasFam (Rec a) (Fam a) where
```

However, the following instance is equivalent, and it is accepted by GHC:

```haskell
instance (b ~ Fam a) => HasFam (Rec a) b where
```

It seems like there would be no reason to not *always* generate instances like that, though it might be theoretically possible to statically check if there are type synonym family applications in the field’s type and only generate the constraint in those situations.

**Comment by glguy** [comment]
This wouldn't be a good idea in general, it would require all users of makeFields to enable `UndecidableInstances` and `TypeFamilies` (for the `~`). It might be worth doing if we know the code will fail otherwise.

**Comment by lexi-lambda** [comment]
Ah, I had considered the potential need for `TypeFamilies` (though I forgot if it was necessary for `~` and hadn’t bothered to check), but I had overlooked `UndecidableInstances`. That makes sense, though—both those extensions would be necessary for the instance in question even if GHC supported it directly, so it wouldn’t hurt to do it selectively.

**Comment by RyanGlScott** [comment]
Trying to automatically figure out when this workaround is necessary sounds an awful lot like type inference, which I'd be loathe to implement in Template Haskell. Perhaps this should be configurable via `LensRules`?

**Comment by lexi-lambda** [comment]
It doesn’t need anything nearly so complex, does it? It merely requires recursively traversing the type and using `reify` to determine if any `ConT`s are the name of a type synonym family. It might also need to expand type synonyms, but that seems like it to me, unless I’m overlooking something significant (which is entirely possible).

**Comment by RyanGlScott** [comment]
Sorry, I don't know what I was thinking in https://github.com/ekmett/lens/issues/754#issuecomment-318519419. What you've described seems quite doable.
