### ISSUE TITLE
Make dimapping right associative

### ISSUE THREAD

**Issue by janpath** [ekmett/lens#758]
The motivation for this would be, so we can write something like this:

    combining :: AnIso' s a -> Iso' (s -> s -> s) -> (a -> a -> a)
    combining i = from i `dimapping` from i `dimapping` i

Instread of:

    combining i = dimapping (from i) . dimapping (from i) $ i

This would also be nice for `dimap`:

    dimap3 :: (a' -> a) -> (b' -> b) -> (c -> c') -> (a -> b -> c) -> (a' -> b' -> c')
    dimap3 a b c = a `dimap` b `dimap` c

Or maybe one could add an operator for it, to avoid the breaking change. But maybe it is not worth it.

**Comment by glguy** [comment]
I think it makes for surprising code when people set custom fixities on backticked identifiers. In the first example I'd prefer simply to have the parentheses.

**Comment by janpath** [comment]
@glguy The big advantage is that it scales to any number of arguments, whereas with left associativity you have to add a pair of parenthesis for every argument.

**Comment by glguy** [comment]
I agree they are not unprecedented. `elem` is another example. I'm simply saying they are a bad idea, especially for uncommonly used identifiers. Getting to drop some parentheses in one case is not worth the surprise that it adds to the code.

**Comment by janpath** [comment]
I now think `dimapping` should have the same fixity as `dimap`, but I still think changing the fixity of `dimap` is worth it. It is not just saving the occasional parenthesis, but creating a combinator for intuitive manipulation of any argument of arbitrarily complicated functions.

Consider for example the following:

    f :: (a' -> a) -> (b -> b') 
      -> (a  -> (b  -> (a  -> b ) -> a ) -> b )
      -> (a' -> (b' -> (a' -> b') -> a') -> b')

Implementing f would be a pain normally, but with right associative dimap it is straightforward:

    f a b = a `dimap` (b `dimap` (a `dimap` b) `dimap` a) `dimap` b

If dimap is left associative it is not as readable:

    f a b = a `dimap` ((b `dimap` ((a `dimap` b) `dimap` a)) `dimap` b)
    f a b = a `dimap` (b `dimap` (a `dimap` b `dimap` a) `dimap` b)

Sure this function is contrived, but I do think it is a common usecase to manipulate some arguments somewhere in a complicated function and I am not aware of a nice way to do this.

**Comment by ekmett** [comment]
I'm somewhat leery of changing fixities retroactively, as it means that anybody that was using `dimap` even infix even just one time, amid other operators now risks a change in meaning.

**Comment by janpath** [comment]
Maybe one could make it `infix` for a few versions. That would make sure that no code silently breaks and will force users to change their code in a backwards compatible way.

**Comment by Taneb** [comment]
I think that the motivating examples for this issue are all more clearly written without using `dimap`/`dimapping` whatsoever. It's not a function commonly used infix, and as such it would take me a few moments to figure out what's going when used infix.

**Comment by janpath** [comment]
@Taneb You are right, this is not a common use currently. But once you understand the pattern it is very intuitive. Also I do not see how you would write the last example more clearly or even remotely as clear without dimap.

**Comment by phadej** [comment]
If the infix trickery is useful only with `(->)` as a `Profunctor`, then it's not worth it. :-1:

**Comment by janpath** [comment]
@ekmett It seems very unlikely to me, that changing the fixity of dimap would silently break code anyway.

If we have an expression like this:

    v `op1` x `dimap` y `op2` z

With op1, dimap and op2 having the same fixity, so that associativity is important. This is only allowed, if they also have the same associativity, so if we change the associativity of dimap this code would break at compile time unless the associativity of op1 and op2 changes as well. This only seems likely, if op1 = op2 = dimap. But in this case we get the following expressions:

    (x `dimap` y) `dimap` z :: p (p x y) z -> _ -- before
    x `dimap` (y `dimap` z) :: p x (p y z) -> _ -- after

Since these expressions have different types, it seems unlikely that replacing before with after would not break at compile time to me.

@phadej  You are right, it is most useful for `(->)`. One could argue, that profunctors are mostly similar to `(->)` and therefore it is natural to think of them as right associative, but it is somewhat of a stretch. I just think it would make for a very useful combinator that we could get for relatively cheap.

**Comment by ekmett** [comment]
I'm pretty convinced that silent semantic changes won't occur now. If it wasn't a 9 then there'd be additional cases to consider.

I still think that it'd be a pretty hard parse for someone to make and requires looking up a buried fixity declaration that shows up in no documentation. An operator might be clearer.

**Comment by janpath** [comment]
@ekmett Ok. How about `(-/>)` for `dimap` and `(~/>)` for `dimapping`? Neither Hoogle, Hayoo, or Stackage know those operators.

For precedence I think it should be higher than 4, because using `(<$>)` and the like in between `(-/>)` seems less likely than wanting to lift some `(-/>)`-expression over a functor. It should also be lower than 9, so that one can use `(.)` without needing parenthesis. For `(~/>)` it would be useful, if it had a precedence higher than that of `(#)`, but because there is no 9.5 precedence I think it should be lower than 8 in order to be less confusing when one tries to mix `(#)` with `(~/>)`. So I think the precedence should be between 7 and 5.

**Comment by glguy** [comment]
Rather than grabbing more operators in a common package, these could be defined locally in the module that needs them. This would have the benefit of making them more discoverable for the reader of that module.

**Comment by janpath** [comment]
@glguy It also makes you less likely to use them or know about them and thus harder to read if they occur. If you just define them locally you may also be too lazy to document them. If they are defined in a package you will get nice documentation with a few usage examples.

**Comment by janpath** [comment]
Here is another motivating example from `lens`. What is the type of this code?

    func l f = rmap phantom . l $ rmap phantom f

<details> 
  <summary>How about this formulation?</summary>

    func = (id -/> phantom) -/> id -/> phantom

</details>

<details> 
  <summary>Original</summary>
From Control.Lens.Getter:

    getting :: (Profunctor p, Profunctor q, Functor f, Contravariant f)
            => Optical p q f s t a b -> Optical' p q f s a
    getting l f = rmap phantom . l $ rmap phantom f

</details>

Writing this I noticed, that `(-/>)` looks a bit like the arrow is crossed out. Maybe `(-*>)` is better.

**Comment by ekmett** [comment]
I confess, the more I look at examples, the less I'm inclined to take an
operator in a very heavily used package where it'll cause headaches for any
user that doesn't expect it. (-/->) or (-/>) is probably the least bad of
the bunch if we did decide to go with it. (Once you start putting *'s in
it, etc. it doesn't read as anything related to profunctors to me.)

That said, an arrowish notation like that would tend to imply infixr 0.
This might not be bad, as it lets you do more stuff infix without parens
inside arguments.
