### ISSUE TITLE
Add `getter = to` alias

### ISSUE THREAD

**Issue by phadej** [ekmett/lens#759]
`getter` would be in line with `lens` and `prism`, (`traversal = id`). Something prevents me of re-exporting `to` from our internal prelude, but we have `getter`.

```haskell
foo :: Getter Bar Fooo
foo = getter $ \b -> b ^. fo <> b ^. oo
```

I can make a PR if this change is ok.

**Comment by emilypi** [comment]
We could probably close this en lieu of the discussion here: https://github.com/ekmett/lens/pull/830
