### ISSUE TITLE
Steal `op`

### ISSUE THREAD

**Issue by ekmett** [ekmett/lens#768]
https://hackage.haskell.org/package/newtype-0.2/docs/Control-Newtype.html#v:op

We raided the rest of the `newtype` package for combinators. But we're missing that one.

(If folks think the name is too common we _could_ exile it to `Control.Lens.Extras`.)

**Comment by ekmett** [comment]
(Suitably generalized to use the _Wrapped machinery)

**Comment by Taneb** [comment]
I'm a bit confused by this, did you just miss that https://github.com/ekmett/lens/blob/master/src/Control/Lens/Wrapped.hs#L1278 already exists?

**Comment by ekmett** [comment]
Yep.
