### ISSUE TITLE
Add Monoid requirement to Cons/Snoc?

### ISSUE THREAD

**Issue by Zemyla** [ekmett/lens#786]
All of the instances for `Cons` seem to be `Monoid`s, and the laws relating them would be:

```haskell
uncons mempty ≡ Nothing
unfoldr uncons (mappend x y) = mappend (unfoldr uncons x) (unfoldr uncons y)
```

Similar laws would apply to `Snoc`'s `Monoid` prerequisite. All of the existing instances for `Cons`/`Snoc` are `Monoid`s anyway, and I don't think there are any user-defined ones outside this project that break it either.

**Comment by Taneb** [comment]
I think this is wrong. Consider `data Stream a = a :< Stream a`. This admits a sensible and obvious `Cons` instance, but not your suggested `Monoid` instance.

**Comment by ekmett** [comment]
Taneb's counter example is the same one that came to mind for me.

The monoid for infinite streams needs to zip with the value-level monoid.
