### ISSUE TITLE
Consider a cleaner holesOf implementation

### ISSUE THREAD

**Issue by treeowl** [ekmett/lens#788]
The implementation of `holesOf` is not the cleanest thing. In particular, it uses `unconsWithDefault` in a context where the default will never be chosen, because it loses track of the length of the traversal. I have no idea how to deal with the current `holesOf` type, but I figured I would demonstrate that it's possible to implement a reasonably efficient old-school `holesOf` without that particular ugliness.

I'll start with a way to reassociate `Applicative` operations.

```haskell
newtype Grump f a = Grump {runGrump :: forall b c. (a -> b -> c) -> f b -> f c}

instance Functor (Grump f) where
  fmap f (Grump g) = Grump $ \h xs -> g (h . f) xs

instance Functor f => Applicative (Grump f) where
  pure x = Grump $ \g xs -> fmap (g x) xs
  liftA2 f xs ys = Grump $
    \g ps -> runGrump xs (\a ~(m,n) -> g (f a m) n) (runGrump ys (,) ps)

liftGrump :: Applicative f => f a -> Grump f a
liftGrump xs = Grump $ \f ys -> liftA2 f xs ys

lowerGrump :: Applicative f => Grump f a -> f a
lowerGrump gr = runGrump gr const (pure ())
```

Now we can make a version of the classic `FunList` with a little `Coyoneda` embedded to make it lazier:

```haskell
data FL a t where
  D :: t -> FL a t
  M :: (a -> r -> t) -> a -> FL a r -> FL a t

runFL :: FL a t -> t
runFL (D t) = t
runFL (M g a xs) = g a (runFL xs)

instance Functor (FL a) where
  fmap f (D t) = D (f t)
  fmap f (M g a ys) = M (\a' r -> f (g a' r)) a ys

instance Applicative (FL a) where
  pure = D
  liftA2 f (D x) ys = f x <$> ys
  liftA2 f (M g a l) ys =
    M (\a' ~(r,b) -> f (g a' r) b) a $ liftA2 (,) l ys
```

Now we get to the meat of the matter:

```haskell
bp :: a -> FL a a
bp a = M const a (D ())

hl :: FL a t -> [Context a a t]
hl = go id
  where
    go :: (t -> u) -> FL a t -> [Context a a u]
    go _ (D _) = []
    go f (M g a as) = Context (\a' -> f $ g a' $ runFL as) a :
         go (\h -> f (g a h)) as

holesOf :: forall s t a. LensLike (Bazaar a a) s t a a -> s -> [Context a a t]
holesOf f s = hl . lowerGrump $ runBazaar (f sell s) (liftGrump . bp)
-- We use Grump to avoid badly-associated FL appends.
````

**Comment by treeowl** [comment]
Here's an arguably cleaner way to reassociate. I haven't benchmarked it against `Gump`, but it seems to preserve the necessary laziness without adding extra structure, which is cleaner.

```haskell
newtype Grump f a = Grump {runGrump :: forall b c. (a -> b -> c) -> f b -> f c}

instance Functor (Grump f) where
  fmap f (Grump g) = Grump $ \h xs -> g (h . f) xs
instance Functor f => Applicative (Grump f) where
  pure x = Grump $ \g xs -> fmap (g x) xs
  liftA2 f xs ys = Grump $
    \g ps -> runGrump xs (\a ~(m,n) -> g (f a m) n) (runGrump ys (,) ps)

liftGrump :: Applicative f => f a -> Grump f a
liftGrump xs = Grump $ \f ys -> liftA2 f xs ys

lowerGrump :: Applicative f => Grump f a -> f a
lowerGrump gr = runGrump gr const (pure ())
```

**Comment by treeowl** [comment]
My original version was a bit too strict to handle partially-defined lists properly. Fixed now!

**Comment by phadej** [comment]
`Grump f` is `Day f f` btw.

**Comment by treeowl** [comment]
@phadej, which `Day`? I don't see one that looks very similar.

**Comment by treeowl** [comment]
Side note for future me: there's a very easy (but small) optimization:

```haskell
liftGrump . bp = \x -> Grump $ \f ys -> M f x ys
```

**Comment by treeowl** [comment]
@phadej, ah, I guess it's pretty similar to `Data.Functor.Day.Curried`, but I'm not sure how to actually demonstrate a laziness-preserving isomorphism.

**Comment by phadej** [comment]
```
{-# LANGUAGE RankNTypes #-}

newtype Curried f f' a = Curried (forall   c.                  f (a -> c) -> f' c)
newtype Grump    f   a = Grump    (forall b c. (a -> b -> c) -> f b        -> f  c)

toGrump :: Functor f => Curried f f a -> Grump f a
toGrump (Curried f) = Grump $ \abc fb -> f (fmap (flip abc) fb)

toCurried :: Grump f a -> Curried f f a
toCurried (Grump f) = Curried $ \fac -> f (flip id) fac
```

I guess your `Grump` is "better" for what you do. My comment was merely, why it's `Grump` and not something `Day` related (note, that's a surname)

**Comment by treeowl** [comment]
The only reason is ignorance on my part! Do you have a name to suggest?

**Comment by phadej** [comment]
In http://hackage.haskell.org/package/lens-4.16/docs/Control-Lens-Traversal.html#v:confusing it's simply `Curried Yoneda Yoneda` :)

**Comment by treeowl** [comment]
@phadej, that's definitely too strict for my purpose!  Do you think maybe you could help me adapt my implementation to the type `holesOf` now has in `lens`? I don't really know anything about `Conjoined` profunctors or even indexed optics, so the non-`(->)` case is utterly mysterious to me.

**Comment by phadej** [comment]
I'm not sure I'm any better in following the types than you are :/

To get indexed optic, replace `_ -> f _` with `Indexed i _ (f _)` http://hackage.haskell.org/package/lens-4.16/docs/Control-Lens-Internal-Indexed.html#t:Indexed In a nutshell that's all Conjoined does, abstracts over `Indexed i` and `(->)`.

**Comment by treeowl** [comment]
@phadej, in case this helps:

```haskell
holesOf :: forall p s t a. Conjoined p => Over p (Bazaar p a a) s t a a -> s -> [Pretext p a a t]
holesOf l s = unTagged
  ( conjoined
      (Tagged (hl (lowerGrump $ runBazaar b (liftGrumpBP)) :: [Pretext (->) a a t]))
      _ -- ??????????
    :: Tagged (p a b) [Pretext p a a t]
  ) where
      b = l sell s
```

**Comment by treeowl** [comment]
I'm not 100% sure I need the extra laziness in `Dayly` here. I should check that.
