### ISSUE TITLE
the fact that `view` works with Prisms is surprising

### ISSUE THREAD

**Issue by gelisam** [ekmett/lens#798]
A colleague recently wrote the following to extract the field "foo" from a json structure.

    getFoo :: Aeson.Value -> Text
    getFoo = view (key "foo" . _String)

I explained that since we are not certain that the json will contain a key named "foo" and that this field will contain a string, it would be better to return a `Maybe Text`, using `preview` instead of `view`. But why does the above type-check in the first place? Since ` _String` is a Prism, not a Getter, shouldn't we be forced to use `preview` instead of `view`?

It turns out that `view` behaves like `foldOf`: when given a Traversal, it `mappends` all the elements together. In particular, since `key "foo" . _String` is a Traversal, if the json does not contain a key named "foo" or if this field does not contain a string, `view (key "foo" . _String)` will traverse zero elements and will return `mempty`, in this case the empty string.

As the example above demonstrate, this is error prone. I would prefer if `view` had this more restricted type:

    view :: MonadReader r m => Getter r a -> m a
    view = view

But I realize that due to backwards compatibility, the type of `view` is unlikely to change. Would you instead be open to the possibility of a PR which adds a `view1` operator with this type signature? I could then warn my colleagues to never use `view`, and to instead always use `view1` or `foldOf` in order to clarify whether they intend to get a single value which is definitely there or to `mappend` together many values.

*edit*: I previously claimed that `key "foo" . _String` was a Prism. `_String` is a Prism, but `key "foo" . _String` is a Traversal.

**Comment by phadej** [comment]
@gelisam note that there's also https://www.stackage.org/haddock/lts-10.9/lens-4.15.4/Control-Lens-Fold.html#v:first1Of which doesn't work with `Prisms` (and given how seldom someone uses Fold1 or Traverse1) it could suit you today. We could generalise the signature of `firstOf1` to use `MonadReader` though.

```haskell
λ *Control.Lens> first1Of _1 ('a', 'b')
'a'
λ *Control.Lens> first1Of folded ('a', 'b')

<interactive>:8:10: error:
    • No instance for (Monoid (Data.Semigroup.First Char))
        arising from a use of ‘folded’
      There are instances for similar types:
        instance Monoid (Data.Monoid.First a) -- Defined in ‘Data.Monoid’
    • In the first argument of ‘first1Of’, namely ‘folded’
      In the expression: first1Of folded ('a', 'b')
      In an equation for ‘it’: it = first1Of folded ('a', 'b')
```

**Comment by gelisam** [comment]
Thanks, `first1Of` works like a charm!
