### ISSUE TITLE
makeFields instances violate coverage condition

### ISSUE THREAD

**Issue by bergey** [ekmett/lens#799]
`makeFields` generates instances with `TF foo ~ a` constraints for data families.  These require UndecidableInstances, but the more obvious version works without that extension.

I'm using `lens-4.15.4` and GHC 8.2.  I haven't yet tested with other versions.  

I suspect this behavior was introduced in https://github.com/ekmett/lens/issues/754 (Based on reading that thread, not trying earlier versions of lens.) Maybe it's possible to distinguish type families from data families, and be less eager to use the equality constraint?  I'm at the limit of my knowledge of TH, unfortunately.

Short example below.  In my actual use, I have the `Key` family from `persistent`, as the data family causing me trouble.

```
module Experiment where

class HasFoo s a | s -> a where
    foo :: s -> a

data family DF a
newtype instance DF Int = FooInt Int

data Bar = Bar {
    _foo :: DF Int
    }

-- | Type checks
instance HasFoo Bar (DF Int) where
    foo = _foo

-- | Does not typecheck without UndecidableInstances

-- instance a ~ DF Int => HasFoo Bar a where
--     foo = _foo

--     • Illegal instance declaration for ‘HasFoo Bar a’
--         The coverage condition fails in class ‘HasFoo’
--           for functional dependency: ‘s -> a’
--         Reason: lhs type ‘Bar’ does not determine rhs type ‘a’
--         Un-determined variable: a
--         Using UndecidableInstances might help
--     • In the instance declaration for ‘HasFoo Bar a’
--    |
-- 20 | instance a ~ Foo Int => HasFoo Bar a where

```

**Comment by RyanGlScott** [comment]
Yes, good catch. Indeed, the code which currently decides whether to emit an equality constraint or not:

https://github.com/ekmett/lens/blob/9d1d2e6236c06dd48fadbf199e871b1f64e61123/src/Control/Lens/Internal/FieldTH.hs#L386-L389

Does not distinguish between type families and data families. We really should exclude data families, just as we exclude normal data types.

**Comment by bergey** [comment]
Thank you for the impressively fast turnaround on that patch & test!

**Comment by RyanGlScott** [comment]
I've uploaded [`lens-4.16.1`](http://hackage.haskell.org/package/lens-4.16.1) to Hackage with a fix.
