### ISSUE TITLE
filteredHas combinator

### ISSUE THREAD

**Issue by yairchu** [ekmett/lens#806]
I'm suggesting this combinator:

    filteredHas :: Lens.Fold s i -> Lens.IndexedTraversal' i s s
    filteredHas fold f val =
        case val ^? fold of
        Nothing -> pure val
        Just proof -> Lens.indexed f proof val

It can replace code like this:

    Lens.filtered (Lens.has part) %~ \x -> something (x ^?! part) x

With `filteredHas part %@~ something`. I think it's quite useful and am using it on an expression tree sugaring pass.

Disclaimer: It's quite possible it already exists and I just haven't found it, or has a very succinct way to write it that makes it unnecessary. I often have difficulty finding combinators in `lens`.

**Comment by ekmett** [comment]
It doesn’t really pass the Fairbairn threshold for me, but it’s come up enough that I’m open to it.

Maybe filteredBy would read better?

**Comment by yairchu** [comment]
`filteredBy` LGTM, shall I create a PR?

**Comment by ekmett** [comment]
The problem with `filteredBy` taking `(a -> Maybe b)` is that then the common usecase still requires a call to `preview` inside it, exploding it back to the same number of "words" has before with `has`.

**Comment by ekmett** [comment]
`filteredBy (preview x)` is longer than `filtered (has x)`

**Comment by glguy** [comment]
That's true that it's longer, but the `filteredBy` version is supposedly more useful because it puts the extracted value into the index. Access to that value in the index is the only reason I think it's worth defining this in the first place.

**Comment by ekmett** [comment]
@yairchu: Subject to the two bullet points raised by @glguy, sure.

**Comment by ekmett** [comment]
I've been asked for some flavor of this about every 2-3 months for a couple of years now. Exposing the filtered part as an index finally gave me enough of an excuse to say yes. ;)

**Comment by yairchu** [comment]
I'm stuck on the PR, due to having trouble to make the types work for this simple example which I came up with for the doc-test:

    >>> [(Just 2, 3), (Nothing, 4)] <&> filteredBy (_1 . _Just) . _2 %@~ (*)

This neither works with the type mentioned above nor with the more general

    filteredBy :: (Indexable i p, Applicative f) => Getting (First i) a i -> p a (f a) -> a -> f a

I'm afraid I haven't yet mastered the different lens types and need some advice here..

(Note that I have been successfully using this combinator in my own code and haven't noticed this issue)

**Comment by yairchu** [comment]
@glguy oh oops :) thanks!

**Comment by Peaker** [comment]
This is also very useful for indexing one part of the structure while modifying another, without any filtering, e.g if we want to divide a monster's health by its age:

```
monster .> filteredBy monsterAge <. monsterHealth %@~ (/)
```

I would also say that traversing via prisms/etc is also a similar kind of "filter" to this one.

Perhaps it would make sense to:
1) Rename `filteredBy` to `toIndex`
2) Instead of putting the first match into the index, behave like (^.) and put the `mconcat` of the matches

**Comment by yairchu** [comment]
Added in https://github.com/ekmett/lens/pull/807 (as `filteredBy`)
