### ISSUE TITLE
Add Generic Isos

### ISSUE THREAD

**Issue by treeowl** [ekmett/lens#818]
```haskell
generic :: Generic a => Iso' a (Rep a x)
generic = iso G.from G.to

generic1 :: Generic1 f => Iso' (f a) (Rep1 f a)
generic1 = Is on.from1 G.to1
```

I don't know what the names should be.

**Comment by ocharles** [comment]
Isn't this https://hackage.haskell.org/package/lens-4.17/docs/GHC-Generics-Lens.html#v:generic ?

**Comment by treeowl** [comment]
@ocharles, just looked in the wrong place!

**Comment by phadej** [comment]
@treeowl at least you picked the exact same names, so they are good ;)
