### ISSUE TITLE
Inconsistency in au/auf?

### ISSUE THREAD

**Issue by twhitehead** [ekmett/lens#821]
For `ala` and `alaf` we have a nice consistency

```
>>> ala Sum foldMap [1,2,3,4]
10
>>> alaf Sum foldMap Prelude.length ["hello","world"]
10
```

but not so for `au` and `auf`

```
>>> au (_Wrapping Sum) foldMap [1,2,3,4]
10
>>> auf (_Unwrapping Sum) (foldMapOf both) Prelude.length ("hello","world")
10
```

Possibly the iso in one of these is backwards (e.g., `au` should be `_Unwrapping` or `auf` should be `_Wrapping`)?

**Comment by twhitehead** [comment]
For what it's worth, to me it seems that there are two issues at play here.

# Two `Iso` naming conventions in place

1 - general `Iso`s are named after their right-hand-side (e.g., `enum`, `curried`, etc.),
2 - wrapper `Iso`s are named after their left-hand-side (e.g., `_Wrapping Sum`, etc.)

Personally I prefer the first as, the following lines give what I would expect
```
65 ^. enum :: Char = 'A'
(+) ^. uncurried $ (4,5) = 4+5
```
were this is not what I expect
```
Sum 2 ^. _Unwrapping Sum = Sum (Sum 2)
```

# Direction of `Iso` passed to `au` is backwards

So, while it would seem at first glance like `au` is the one that makes sense and `auf` is backwards
```
au (_Wrapping Sum) foldMap [1,2,3,4] = 10
auf  (_Unwrapping Sum) foldMap id [1,2,3,4] = 10
```
this is actually just an artifact of the fact that `_Wrapping` and `_Unwrapping` are not what you would expect.  It is `auf` that is consistent with other functions (e.g., `^.`) while `au` is not.  This becomes even more evident if we consider a more complex example
```
au (_Wrapping Max . enum) map foldMap "hello world" = 'w'
auf  (from enum . _Unwrapping Max) foldMap id "hello world" = 'w'
```
where now we really see that `au` has us specify the entire `Iso` backwards.  Both in terms of the direction of composition and the names of the components.

**Comment by twhitehead** [comment]
To be 100% clear, my ideal world would be (for reasons I do not understand, binding `_Wrapping` and `_Unwrapping` to new names gives functions that do not work in place of the originals in ghci, while re-entering their definitions does)
```
au_ = au . from
_Unwrapping_ = _Wrapping
_Wrapping_ = _Unwrapping
```
so
```
au_ (from enum . _Wrapping_ Max) foldMap "hello world" = 'w'
auf (from enum . _Wrapping_ Max) foldMap id "hello world" = 'w'
```

**Comment by emilypi** [comment]
This came up in conversation recently, and I happen to agree. However, it'd be a breaking change for whoever uses it. If there is a major version bump coming up soon, this would be a good thing to change.

**Comment by RyanGlScott** [comment]
I'm somewhat unclear on what exact change is being proposed here. In https://github.com/ekmett/lens/issues/821#issuecomment-431260724, I'm not sure if you're proposing to change the type of `au`, `_Unwrapping`, `_Wrapping`, or suggesting to add new functions named `au_`, `_Unwrapping_`, and `_Wrapping_`.

I bring this up since a new major version of `lens` will likely be released within the coming weeks, so if this change deserves to make it in the next release, we should consider doing so soon.

**Comment by twhitehead** [comment]
The underscores where just to separate the new definitions from the existing ones. I wasn't meaning proposing new definitions. Of course, if whoever is in charge things that would be the best thing to do, then that is what they should do.

Personally, I would change the definition of `au` for sure so the `Iso` doesn't have to be composed backwards for sure. I'm going to guess this function hasn't actually been used a lot, or I'm sure someone else would have brought this up before, so hopefully this wouldn't be too breaking.

Ideally `_Wrapping` and and `_Unwrapping` could be swapped as well. I expect that would actually break quite a bit of code though, so maybe that isn't realistic.

**Comment by RyanGlScott** [comment]
I see. I can certainly sympathize with the desire for consistency, although it's worth noting that the type signature of `au` was deliberately designed to closely mirror that of [`ala` from the `newtype` package](https://hackage.haskell.org/package/newtype-0.2.1.0/docs/Control-Newtype.html#v:ala). We'd be deviating from that intended resemblance a bit if we implement this proposed change. Whether anyone would care about this in practice is unclear to me.

Thoughts on this, @ekmett?

**Comment by ekmett** [comment]
I agree that there is an infelicity here!

I disagree about the direction of the correction.

It argue that `Iso`s are generally better considered as generalized prisms than as generalized lenses, especially for this purpose. `au`/`auf` are intended to work with `_Wrapped Sum` and the like which behave like "prisms" for the newtype constructor. `au`/`auf` _should_ work with Isos that follow the prism naming convention, such as `_Sum` and the like. This best mirrors the behavior of the `newtype` package and the behavior of `ala` / `alaf` and the documentation.

I'd argue that the reason this slipped through is that we've just never really used auf much in practice.

I'd actually be open to doing a breaking change to the semantics of `auf` clearly marked in the next major release of `lens` as this one is pretty blatantly wrong by the original intended spec of the function.

The only minor annoyance in the whole affair is that `auf` then becomes a little more complicated than `coerce`. =)

**Comment by ekmett** [comment]
I've now somewhat paged in the original reasoning that led to the flipped `auf`.

In its current form it gives a name to the combinator that takes a Iso to the "pair of functors" style:

`(f a -> g b) -> f s -> g t`

which as I recall was an observation by James Deikun.

This does leave us hoist on a bit of a dilemma. To serve its stated purpose, it should be flipped to use `coerce from` but to give a canonical version of this conversion it should keep its same direction.

I'm still leaning towards flipping it to the other convention and coining a new name for the combinator that performs its existing 'coerce' based behavior, despite this being a breaking change to the API.

**Comment by phadej** [comment]
The current version is 4.17.1, so the next could be 4.18; not 4.19.
