### ISSUE TITLE
Add `Either` instance for classy prisms

### ISSUE THREAD

**Issue by parsonsmatt** [ekmett/lens#838]
I wrote about [the downsides of classy prisms](https://www.parsonsmatt.org/2018/11/03/trouble_with_typed_errors.html). To summarize, there currently is not a way to "subtract" a constraint from an error type. Error constraints can only accumulate, which means that there is no way to `catch` an error in the types. `generic-lens` defines (generically) an instance for `AsType a s` for the `Either` type, which lets you "pluck" constraints one-by-one, in much the same way as `runStateT` "plucks" a `StateT` constraint off a monad stack.

`lens` could also solve this problem by including (in the `makeClassyPrisms` Template Haskell declaration) instances for `Either`. An example is included here:

```haskell
{-# LANGUAGE FlexibleContexts       #-}
{-# LANGUAGE FlexibleInstances      #-}
{-# LANGUAGE FunctionalDependencies #-}
{-# LANGUAGE MultiParamTypeClasses  #-}
{-# LANGUAGE TemplateHaskell        #-}
module Prisms where

import           Control.Lens
import           Control.Monad.Error.Lens
import           Control.Monad.Trans.Except

data FooBar = Foo Int | Bar Char

data BazQuux = Baz String | Quux Double

makeClassyPrisms ''FooBar
makeClassyPrisms ''BazQuux

instance {-# OVERLAPPING #-} AsFooBar (Either FooBar x) where
    _FooBar = _Left

instance {-# OVERLAPPABLE #-} AsFooBar x => AsFooBar (Either a x) where
    _FooBar = _Right . _FooBar

instance {-# OVERLAPPING #-} AsBazQuux (Either BazQuux x) where
    _BazQuux = _Left

instance {-# OVERLAPPABLE #-} AsBazQuux x => AsBazQuux (Either a x) where
    _BazQuux = _Right . _BazQuux

program
    :: (Monad m, AsFooBar e, AsBazQuux e)
    => ExceptT e m ()
program = do
    throwing _Foo 3
    throwing _Baz "Hello"

program'
    :: (Monad m, AsBazQuux e)
    => ExceptT e m ()
program' = do
    program `catchE` \err ->
        case err of
            Left (Foo i) ->
                throwing _Quux (fromIntegral i)
            Left (Bar c) ->
                throwing _Baz [c]
            Right e ->
                throwE e
```

This issue is a request to add the two `Either` instances for each generated classy prism type. If it is accepted then I would be happy to implement it.

Thanks!

**Comment by glguy** [comment]
I'd prefer to avoid overlapping instances as much as is possible. If we were going to have this I'd like to see it in a separate Template Haskell implementation like: `makeClassyPrismsEither` or added to the rules struct to only make them when specifically enabled.

**Comment by treeowl** [comment]
I'm also wary of overlapping instances in general. I'm *especially* wary of overlapping instances for common types like `Either`. Do you really need to use `Either` for this, or can you write a custom sum type to do the job?

**Comment by ekmett** [comment]
That said, nothing stops you from doing this for your own types in your own projects.

**Comment by parsonsmatt** [comment]
Yeah, this should live somewhere else :)
