### ISSUE TITLE
Control.Lens.filtered: When is it a legal `Prism`?

### ISSUE THREAD

**Issue by endgame** [ekmett/lens#839]
Documentation says:

> Obtain an Fold that can be composed with to filter another Lens, Iso, Getter, Fold (or Traversal).
>
> Note: This is not a legal Traversal, unless you are very careful not to invalidate the predicate on the target.
>
> Note: This is also not a legal Prism, unless you are very careful not to inject a value that matches the predicate.

The second note confuses me: it is only a valid `Prism` if you _don't_ inject a value that matches the predicate?

**Comment by ekmett** [comment]
That should say “fails” rather than matches.
