### ISSUE TITLE
Generalise generic1 from GHC.Generics.Lens

### ISSUE THREAD

**Issue by Jashweii** [ekmett/lens#841]
Generalise the type of the iso `GHC.Generics.Lens.generic1`
from `generic1 :: (Generic1 f) => Iso' (f a) (Rep1 f a)`
to `generic1 :: (Generic1 f) => Iso (f a) (f b) (Rep1 f a) (Rep1 f b)`
... to allow changing the type parameter under generic1.

**Comment by ekmett** [comment]
If it works I see no reason not to.
