### ISSUE TITLE
Lifting lenses through Applyable Functors

### ISSUE THREAD

**Issue by dwincort** [ekmett/lens#888]
Hi,

I've often had situations where I have a list of pairs and I want to operate on just the first element of the pair.  This is not so hard if I want to do element-wise operations on these elements — something like `pairList & each . _1 %~ foo` would do the trick — but it's more challenging when I want access to the whole list.  I ended up writing the function I needed:
```haskell
import qualified Control.Monad.Reader as Reader
import Data.Functor.Apply

-- | A combinator for pushing a lens through an `Apply`able functor.
--
-- For instance, a `Lens' Int String` can be turned into a `Lens' [Int] [String]`.
-- (Although keep in mind that if you want zipping semantics, you'll want to use
-- `ZipList` rather than `[]`.)
applyUnder :: Apply f => Lens s t a b -> Lens (f s) (f t) (f a) (f b)
applyUnder l afb s = liftF2 (flip $ set l) s <$> afb (myView <$> s)
  where myView = Reader.asks (getConst . l Const)
```
(The `myView` part is a bit of a wart, but GHC wouldn't properly infer the type if I simply used `view`.)

Now, I can have a function `foo :: [a] -> [b]` and apply it to a value `pairList :: [(a,x)]` with `pairList & applyUnder _1 %~ foo :: [(b,x)]`.  Intuitively, the name `applyUnder` comes from the fact that the given lens is being "applied under" the applyable functor.

I thought this might be something useful to others and worth upstreaming.

### Notes
Actually, most of the time, I want `ZipList` mechanics and not a cartesian product.  Indeed, I designed this operator to be used on something like a `Map`, which is why I am using the less restrictive `Apply` class instead of the more common `Applicative`.  It would be  great if one could write something like `alaf ZipList (applyUnder myLens)`, but that doesn't quite work — the best I could get was `zlIso . applyUnder l . from zlIso` where `zlIso =  iso ZipList getZipList`.

**Comment by dwincort** [comment]
Yes, this definitely has a similar issue to `partsOf` where it's important to maintain the shape of the applyable functor (e.g., length of list, keys in map, shape of tree, etc.), and if that's enough to kill this proposal, I definitely understand.  That said, I'm not sure how to use `partsOf` to do what `applyUnder` does, even in just a list case.

**Comment by ekmett** [comment]
As specced this isn't a legal `lens`. Variations of this do exist for special purposes of `f`. e.g. for a `Representable f` you can use `column` from the `linear` library. for basically everything else you are probably not going to find a legal solution.
