### ISSUE TITLE
generic and generic1's types are too restrictive

### ISSUE THREAD

**Issue by yairchu** [ekmett/lens#890]
Currently

```Haskell
generic1 :: Generic1 f => Iso (f a) (f b) (Rep1 f a) (Rep1 f b)
generic1 = iso from1 to1
```

While it could had been less restrictive with the exact same implementation:

```Haskell
generic1 :: (Generic1 f, Generic1 g) => Iso (f a) (g b) (Rep1 f a) (Rep1 g b)
generic1 = iso from1 to1
```

For an example use-case see https://github.com/lamdu/hypertypes/blob/master/src/Hyper/Class/Functor.hs#L37

Currently it uses a `to1 . X . from1` form while it could had been `generic1 %~ X` if `generic1` was more general.

**Comment by glguy** [comment]
Changing this would probably break code that relies on it for type inference. It might be better to have a different definition with the more generalized type?

**Comment by yairchu** [comment]
@glguy though duplication may yield bloat.. I wonder how hard it is to search hackage and github for usages and check if they break, but in any case this may mean a version bump where some breakage for a good cause is probably legitimate? :)

**Comment by glguy** [comment]
The reason it's like it is is to help with type inference, so I'd want to see some examples showing that it's not an issue for common usages before changing it.

**Comment by phadej** [comment]
Simple version can be recovered with `simple`

```haskell
*Control.Lens GHC.Generics.Lens> :t generic
generic
  :: (GHC.Generics.Generic a, GHC.Generics.Generic b, Profunctor p,
      Functor f) =>
     p (GHC.Generics.Rep a c) (f (GHC.Generics.Rep b c)) -> p a (f b) -- Iso a b (Rep a c) (Rep b c)
*Control.Lens GHC.Generics.Lens> :t simple . generic
simple . generic
  :: (GHC.Generics.Generic a, Profunctor p, Functor f) =>
     p (GHC.Generics.Rep a c) (f (GHC.Generics.Rep a c)) -> p a (f a) -- Iso' a (Rep a c)
```

**Comment by yairchu** [comment]
@phadej Wow TIL about `simple`!

**Comment by yairchu** [comment]
Merged! closing
