### ISSUE TITLE
Design questions regarding an improved `at` for Data.Set

### ISSUE THREAD

**Issue by sjakobi** [ekmett/lens#901]
In https://github.com/haskell/containers/pull/682 I'm implementing `Data.Set.alterF` which should be used in `instance At (Set k)` once it's done.

Now a rather subtle design question has come up on whether a key present in the set should be replaced with the search-key or not.

The current instance uses `Data.Set.insert` which _does_ replace the key:

https://github.com/ekmett/lens/blob/eb255ec6c1e5c4f0012ab56268b43a3059d60a16/src/Control/Lens/At.hs#L494-L499

For another instance, the one for `Data.Map`, the behaviour depends on the `containers` version: `Data.Map.alterF` doesn't replace the key, but `Data.Map.insert` will:

https://github.com/ekmett/lens/blob/eb255ec6c1e5c4f0012ab56268b43a3059d60a16/src/Control/Lens/At.hs#L469-L478

Usually it shouldn't matter whether the key is replaced or not – unless the `Ord` instance for the key type ignores some aspect of the keys and equal keys can be observed to be different in some way.

From an implementation perspective, _not replacing_ the key is a bit simpler and potentially slightly more efficient.

Do you have a preference what `Data.Set.alterF` should do?

**Comment by phadej** [comment]
I'd like the `Set` to keep the existing keys, I'm thinking of hash-consing as the use case. It would require having `lookupValue :: Ord a => a -> Set a -> Maybe a` function though.

Or/And having `alterWithKeyF :: Functor f => (a -> Bool -> f Bool) -> a -> Set a -> f (Set a)`, i.e. to have a variant of https://hackage.haskell.org/package/lens-4.18.1/docs/Control-Lens-At.html#v:icontains which returns the index in the container, not given from the outside (I already have that!)

**Comment by sjakobi** [comment]
@phadej Thanks for your opinion! :)

Regarding `lookupValue` and/or `alterWithKeyF`, I'd suggest that you make a feature request at https://github.com/haskell/containers/issues.

**Comment by sjakobi** [comment]
Seems like there's no interest in replacing pre-existing keys. So I'll go with preserving them, which should be good for performance too.
