### ISSUE TITLE
Could you please rename some variables

### ISSUE THREAD

**Issue by 2-5** [ekmett/lens#903]
I was going through the lens docs, and I suddenly got to this section:
https://hackage.haskell.org/package/lens-4.18.1/docs/Control-Lens-Combinators.html#v:indexing

As you may notice, the word `s t a b` appears multiple times in close succession. Immediately my heart beat spiked, my palms started to sweat and I started to feel light headed, despite not being an overly-sensitive persion. I think it's because I'm living in London, which at this moment is having a serious knife crime problem.

So I'd like to suggest renaming these arguments to something else (`p q a b`?).

**Comment by emilypi** [comment]
I can commiserate with the sentiment of this post, but having exposure with the experience and treatment of mental health issues (especially PTSD), I do not agree that this is a good course of action. Instead, I advise you to get in touch with a mental health professional to help manage any trauma you may have experienced, and limit your exposure to any potential triggers until you have the tools to manage them. Asking library authors to manage your triggers for you is at best a bandaid, and is not a manageable solution. 

Feel free to message me for more information and suggestions.

**Comment by glguy** [comment]
Thanks for your thoughtful response, @emilypi
