### ISSUE TITLE
gplate and uniplate do not return the same result

### ISSUE THREAD

**Issue by soupi** [ekmett/lens#905]
Hi, as I understand both `uniplate` and `gplate` can be used to implement `plate` without having to write the instance by hand.

However, it seems that the two do not return the same results:

```hs
{-# LANGUAGE DeriveGeneric, DeriveDataTypeable #-}

import Control.Lens
import Data.Data.Lens
import Data.Data
import GHC.Generics

data Stmt = Block [Stmt] | Print Int deriving (Show, Eq, Data, Generic)

stmt :: Stmt
stmt = Block [Print 1, Print 2]

main :: IO ()
main = do
  print $ universeOf uniplate stmt
  print $ universeOf gplate stmt
```
```
[Block [Print 1,Print 2],Print 1,Print 2]
[Block [Print 1,Print 2]]
```

In seems as if `gplate` does not go deeper into the list. The result I'd expect is the one `uniplate` returns.

This was tested with GHC 8.6.5 and lens-4.18.1

**Comment by phadej** [comment]
http://hackage.haskell.org/package/lens-4.18.1/docs/Control-Lens-Plated.html#t:Plated

See the Note in the docs, gplate is like manual instance you’d write

Note the big distinction between these two implementations.

The former will only treat children directly in this tree as descendents, the latter will treat trees contained in the values under the tips also as descendants!


Hopefully this clarifies

**Comment by soupi** [comment]
Thank you for the clarification. I have a bit of a hard time thinking about a scenario where I'd want the `gplate` behaviour though and also it felt pretty confusing to me that there is one name `plate` that describes two different intuitions.

Also, is there currently any way to get the behaviour of `uniplate` using the Generic method like `gplate`? I have noticed the performance of `gplate` is much better even in cases where the behaviour is similar (when you don't have mutual recursive types).

**Comment by phadej** [comment]
Manual / `gplate` cannot arbitrarily ”look through” other type (constructors). Depending on the POV that’s pro or con. (Think also cases like `Expr (Expr a)`, you don’t even need multiple types)

**Comment by soupi** [comment]
Thank you for the answer.

**Comment by infinity0** [comment]
@soupi I think the following does what you (and I) want:

```haskell
{-# LANGUAGE DeriveTraversable, FlexibleInstances, MultiParamTypeClasses, TemplateHaskell, TypeFamilies, TypeApplications #-}

import Control.Lens (_Wrapped, (<&>), (&), toListOf)
import Control.Lens.TH (makeWrapped)
import Data.Functor.Foldable (Recursive(..), Corecursive(..), Fix(..), unfix)
import Data.Functor.Foldable.TH (makeBaseFunctor)

makeWrapped ''Fix -- this should really just go in recursion-schemes

data Stmt = Block [Stmt] | Print Int deriving (Eq, Ord, Show, Read)
makeBaseFunctor ''Stmt

main :: IO ()
main = do
  let stmt = Block [Print 1, Print 2]
  print stmt
  -- ^ [Block [Print 1, Print 2]]
  let stmtF = cata Fix stmt
  print $ stmt == ana unfix stmtF
  -- ^ True
  let children = stmtF & toListOf (_Wrapped . traverse) <&> ana @Stmt unfix
  print children
  -- ^ [Print 1,Print 2]
```

Actually neither `gplate` nor `uniplate` does what I (and I assume you) want, but the above code does.

What I want is for the traversal to go into all the self-similar items as declared in the static definition of the data type, neither:

> The former will only treat children directly in this tree as descendents

nor:

> the latter will treat trees contained in the values under the tips also as descendants!

which AIUI would also recurse into self-similar values if the type-parameter fits the structure. So in `Expr b` with `b ~ Expr a` it would recurse into the `Expr a` in the `Val` branch, even though this is not part of the static definition of `Expr`.

By using the TH-generated functor `StmtF`, which only deals with self-similar structures appearing in the static `data` definition, we can get the behaviour we want.

**Comment by soupi** [comment]
@infinity0 thanks! This is interesting. However I have decided not to use lens for this kind of use cases after all and instead use uniplate or similar libraries that will give me the behaviour I want.

**Comment by infinity0** [comment]
Great, glad you found a solution. Just to note, my code above is less about `lens` and more about `recursion-schemes`, the `lens` stuff is just glue code, and the important stuff is `makeBasefunctor` and `traverse`. In this case, `traverse` is the analogue of `uniplate` / `gplate` but with the different behaviour as I described. For my use-case I think it's more appropriate, and the `uniplate` combinators are not as flexible as the ones from `recursion-schemes`.

**Comment by infinity0** [comment]
Just another comment for the record, as @phadej pointed out to me on IRC, uses of `cata . Fix` / `ana . unfix` can typically be simplified, and the above code can be simplified to:

```haskell
main :: IO ()
main = do
  let stmt = Block [Print 1, Print 2]
  print $ project stmt & toListOf traverse
  -- ^ [Print 1,Print 2]
```

**Comment by ekmett** [comment]
The fact that these two do have different behaviors is known and expected. 

It comes down to what you want to consider a recursive occurrence of the "same" type for `plate` purposes. When working with syntax trees and the like where I have an abstract variable type I often want to work in the outer syntax tree, even if what I've built is something that happens to have expressions in them in whatever transient variable representation I'm using.

This may deserve being documented more thoroughly, but it is at least intended behavior.
