### ISSUE TITLE
Figure out what to do about the language-haskell-extract dependency

### ISSUE THREAD

**Issue by RyanGlScott** [ekmett/lens#918]
I am not yet able to run `lens`' test suite + GHC 8.10.1 on Travis CI without the use of `head.hackage`. Why, you ask? It is because various test suites depend on `test-framework-th`, which in turn depends on `language-haskell-extract`. Sadly, `language-haskell-extract` [does not build with `template-haskell-2.16.*`](https://github.com/finnsson/template-helper/issues/12), and the maintainer of the library has not been active on GitHub for about two years. Bottom line: `language-haskell-extract` is likely abandonware.

This poses a problem for `lens`. I can see two ways forward:

1. Beg someone to do a package takeover of `language-haskell-extract` and upload a new version.
2. Remove `lens`' dependency on `test-framework-th`. As far as I can tell, that package only provides a mild syntactic convenience in the form of automatic test discovery, so removing it shouldn't be too difficult.

**Comment by phadej** [comment]
I'd do 2. I'm skeptical about automatic test discovery anyway.

**Comment by RyanGlScott** [comment]
(2) definitely seems like the most expedient solution, so I've submitted #920 for that. The good news is that if we ever want to go back to using `test-framework-th`, reverting #920 won't be too difficult.
