### ISSUE TITLE
Should the `At` class have its own key and value types separate from Ixed?

### ISSUE THREAD

**Issue by ddssff** [ekmett/lens#921]
Because there is an `instance Ixed [a]` with `Index [a] ~ Int`, that means that you can't declare `instance At [(k, v)]` with `Index [(k, v)] ~ k`.  Perhaps `At` should have its own index and value types, say `Key` and `AtValue`.  A lot still to work out here of course.

**Comment by phadej** [comment]
I'd rather define

```
newtype AssocList k v = AssocList [(k, v)]
```

and define appropriate `ix` and `at` instances. Because `ix = at . _Just` (when possible) having separate `AtIndex` and `AtValue` would just add more boilerplate for no sufficiently good reason.

**Comment by ddssff** [comment]
Oh, I should have thought of that.

**Comment by ddssff** [comment]
Closing
