### ISSUE TITLE
-Wstar-is-type

### ISSUE THREAD

**Issue by phadej** [ekmett/lens#928]
``` 
   Using ‘*’ (or its Unicode variant) to mean ‘Data.Kind.Type’
    relies on the StarIsType extension, which will become
    deprecated in the future.
    Suggested fix: use ‘Type’ from ‘Data.Kind’ instead.
```

I have used evil trick of 

```haskell
#define Type *
```

for pre GHC-8.0. And we can re-export `Type` from internal prelude. (Not sure if `TH` module will freak out on that).

**Comment by RyanGlScott** [comment]
Personally, I'd prefer just disabling `-Wstar-is-type`, which doesn't really make sense for code that supports pre-8.0 GHCs.

**Comment by phadej** [comment]
Well, at *some point* it would be good to move to `Type` :)

I'm ok with doing it now. Converting stars to Type gives that "finally, I can say I have done something" -feeling.

**Comment by RyanGlScott** [comment]
> Well, at _some point_ it would be good to move to `Type` :)

Indeed. But I think that point should be when we drop support for pre-8.0 GHCs. The evil trick you propose:

> ```haskell
> #define Type *
> ```

Is unfortunately rather unhygienic. In particular, we use a separate data type named `Type` in `Control.Lens.TH` and friends, so we would have to be extremely careful not to let this CPP directive leak into these modules. In my experience, trying to control the scope of CPP is a massive headache. I'd rather not attempt to do so in the first place.

**Comment by ekmett** [comment]
I'm kinda bullish on dropping support for < 8.0, either now or after 9.2 comes out. Old versions of `lens` and my other packages will continue to function for those users and we get to jettison a LOT of cruft. I welcome the ability to flush all sorts of compatibility hacks from my brain.

**Comment by RyanGlScott** [comment]
Sounds good to me! In that case, let's open this issue as a reminder to drop <8.0 support.

**Comment by phadej** [comment]
I think this applies to all of kmettverse which depends on `lens` (e.g. `linear`, `trifecta`, ...)?

**Comment by ekmett** [comment]
Consider this a blanket offer for narrowing the support window across everything I have on github going forward to GHC 8+.

When the support window narrows to put a floor at 8.8 in maybe ~3 years or so, we'll even be able to assume cabal 3ish and could start breaking up `lens` internally into an explosion of public sub-libraries, all in one name on hackage, allowing folks to depend on just what parts they need so long as they ask carefully. THAT will be a good day. I've been fighting the temptation to bring this day closer too fast.

**Comment by RyanGlScott** [comment]
> Consider this a blanket offer for narrowing the support window across everything I have on github going forward to GHC 8+.

Duly noted! I'll start with `lens`, then. See #977.

**Comment by phadej** [comment]
@RyanGlScott note that `distributive` main branch is 8.6+ only. #977 is already great cleanup, but maybe there will be even more stuff. Although GHC-9.2 will be released earlier than `distributive-1` so maybe the pre GHC-8.0 makes sense if you have to go through stuff anyway.

**Comment by RyanGlScott** [comment]
I don't have a strong opinion on what the minimum supported version should be. I just went with 8.0 since that was the [most recent consensus](https://github.com/ekmett/lens/issues/928#issuecomment-789729992) on the topic. We can always remove more CPP later if need be.

**Comment by ekmett** [comment]
As @phadej notes, we'll most likely land at 8.6 because of the new `distributive` having a hard floor there, but yeah, we can always revel in deleting more CPP later. =)
