### ISSUE TITLE
Drop pre-GHC-7.8 support

### ISSUE THREAD

**Issue by phadej** [ekmett/lens#930]
I think it's time. `profunctors` have dropped it. Bolder move would be to drop pre-GHC-8.0 support, that would clean a lot more of CPP. Yet my motivation is to cleanup things around `Coercible`, which is also why `profunctors-5.3` dropped pre-GHC-7.8 support.

GHC-7.8.4 was released on December 23rd 2014, i.e. over fiver years ago.

Opinions, @ekmett @RyanGlScott

**Comment by RyanGlScott** [comment]
No objections on my end.

**Comment by phadej** [comment]
@RyanGlScott do you have any plans for GHC-8.12 compat release yet? I guess this can be open until about then, so others have time to comment. If there are no real objections, then it can be done in the same (major?) release.

**Comment by RyanGlScott** [comment]
> @RyanGlScott do you have any plans for GHC-8.12 compat release yet?

Not any immediate plans, no. Then again, there haven't been any pre-release versions of GHC 8.12, so it's probably far too early to worry about that.

In any case, I don't foresee the changes we'll have to make to support GHC 8.12 intersecting much with the changes we'll need to make to drop old GHC support. If you want to do the latter now, by all means proceed.
