### ISSUE TITLE
Documentation of `lazy` mentions `strict-base-types`.

### ISSUE THREAD

**Issue by phadej** [ekmett/lens#936]
https://hackage.haskell.org/package/lens-4.19.2/docs/Control-Lens-Iso.html#v:lazy

> See http://hackage.haskell.org/package/strict-base-types for an example use.

Yet, with release of 0.4 https://hackage.haskell.org/package/strict, strict-base-types is being deprecated. (I'll soon upload strict-lens package).

So, what to do with `Strict` class in `lens`? Options:

1. Remove it in favor of `Strict`-class from `strict`, define `strict = iso toStrict toLazy`. This requires adding dependency on `strict`.
2. Correct haddock, but leave everything in place
3. Something else?

I'm in favor of going all the way for 1.

**Comment by RyanGlScott** [comment]
I'm mildly supportive of option (1), although I am curious to know how much breakage would entail. Presumably, any library that defines an instance of `lens`' version of `Strict` would need to be migrate their code, right?

**Comment by phadej** [comment]
@RyanGlScott yes, but I'm really only aware of `strict-base-types` doing that :)

**Comment by RyanGlScott** [comment]
Indeed, a quick Hackage search (using [`hackage-download`](https://github.com/nh2/hackage-download)) suggests that there aren't any clients of `lens`' `Strict` besides `strict-base-types`. In that case, full steam ahead with option (1).
