### ISSUE TITLE
Is having lens-pong example justified?

### ISSUE THREAD

**Issue by phadej** [ekmett/lens#956]
`gloss` + `GLUT` is not the lightest dependency for an "example".

**Comment by ekmett** [comment]
I'm somewhat torn. It was literally our first example as I recall.

You shouldn't incur a dep on them unless you actually _build_ the examples, no? Isn't that the point of making all the dependencies per component?

**Comment by phadej** [comment]
I *build* the examples while working `lens` (and in CI).

**Comment by ekmett** [comment]
We could maybe bury it under a flag for 'expensive-examples' and split the baby that way.

**Comment by phadej** [comment]
If it's still build on CI, one still needs to build it. That is my issue. (examples are not even part of `lens` package), so flag doesn't help anything.

I get this as that you want to keep the example in the repository, no problems here.
