### ISSUE TITLE
Safe and Simple

### ISSUE THREAD

**Issue by phadej** [ekmett/lens#959]
As outlined elsewhere, I'm going to traverse kmettverse to make it `build-type: Simple`. As I'm on it, I'll also try to make it explicitly Safe (or Trustworthy). This issue is too track the progress.

### Dependency tree

For now I target only what is below `free`:

![deps](https://user-images.githubusercontent.com/51087/103223918-b5f5af80-492f-11eb-94e3-3655fd87aba3.png)

- Making everything `build-type: Simple` means removing the dependency on `cabal-doctest` (and yellow boxes - `setup` components).
- Making everything explicit Safe means explicitly annotating every module in the dependency tree, and having lower-bounds so dependencies are also explicitly Safe.

### Tasks

Packages in reverse topological order

| package               | build-type       | Explicitly safe                                                                                |
| --------------------- | ---------------- | ---------------------------------------------------------------------------------------------- |
| base-orphans          | Simple           | [0.8.4](https://hackage.haskell.org/package/base-orphans-0.8.4) (technically since 0.3.0)      |
| tagged                | Simple           | [0.8.6.1](https://hackage.haskell.org/package/tagged-0.8.6.1)                                  |
| distributive          | Simple (0.6.2.1) | [0.5.2](https://hackage.haskell.org/package/distributive-0.5.2) (no changelog entry)           |
| indexed-traversable   | Simple           | [0.1.1](https://hackage.haskell.org/package/indexed-traversable-0.1.1)                         |
| transformers-compat   | Simple           | [0.6.6](https://hackage.haskell.org/package/transformers-compat-0.6.6) (technically since 0.5) |
| comonad               | Simple (5.0.8)   | [5.0.8](https://hackage.haskell.org/package/comonad-5.0.8)                                     |
| th-abstraction        | Simple           | [0.4.2.0](https://hackage.haskell.org/package/th-abstraction-0.4.2.0)                          |
| bifunctors            | Simple           | [5.5.9](https://hackage.haskell.org/package/bifunctors-5.5.9)                                  |
| StateVar              | Simple           | [1.2.1](https://hackage.haskell.org/package/StateVar-1.2.1)                                    |
| contravariant         | Simple           | [1.5.3](https://hackage.haskell.org/package/contravariant-1.5.3)                               |
| exceptions            | Simple           | [0.1.1](https://hackage.haskell.org/package/exceptions-0.1.1) "always"                         |
| profunctors           | Simple           | [5.6.1](https://hackage.haskell.org/package/profunctors-5.6.1)                                 |
| hashable              | Simple           | [1.2.7.0](https://hackage.haskell.org/package/hashable-1.2.7.0)                                |
| unordered-containers  | Simple           | [0.2.6.0](https://hackage.haskell.org/package/unordered-containers-0.2.6.0)                    |
| semigroupoids         | Simple (5.3.5)   | [5.3.5](https://hackage.haskell.org/package/semigroupoids-5.3.5)                               |
| transformers-base     | Simple           | [0.4.5.2](https://hackage.haskell.org/package/transformers-base-0.4.5.2) (no changelog)        |
| free                  | Simple           | [5.1.6](https://hackage.haskell.org/package/free-5.1.6)                                        |

### Status

2020-12-31

![deps](https://user-images.githubusercontent.com/51087/103416044-73c9a980-4b8d-11eb-8744-89646ce47959.png)

**Comment by RyanGlScott** [comment]
It occurs to me that you might be waiting for me to cut releases of some of these packages. If so, I apologize for the delay. Should I interpret a "TODO" in the table as "this is awaiting a new Hackage release", and that I should make such a release after you have made a corresponding PR to that repo?

**Comment by phadej** [comment]
**TODO** are just things to do in general.

At this point, I think `th-abstraction` and `contravariant` couldn't be released, but these don't unblock me to anything else: we need to `comonad` too (see graph).

And `comonad` is blocked on `cabal-docspec`, so there is no hurry.

**Comment by RyanGlScott** [comment]
OK. If there's no hurry, then I'll default to waiting until someone explicitly asks for a new release. Thanks again for picking this up!

**Comment by phadej** [comment]
Well... if we sort `comonad` `cabal-docspec` soon, then I'll ask :)

**Comment by phadej** [comment]
My next request is for releases of
- `semigroupoids` and
- `profunctors`

Which are needed for `free`.

**Comment by phadej** [comment]
safe and simple free. Maybe someone could come up with some pun.

As mentioned on IRC I'll continue work on `cabal-docspec`(ing the kmettverse), but it's not worth tracking the rest.

(FWIW, making `lens` Safe could be viable too, but that effort is somewhat blocked by `adjunctions` being in unclear state)
