### ISSUE TITLE
Should we (gradually) add -Wno-star-is-type to ekmett packages?

### ISSUE THREAD

**Issue by phadej** [ekmett/lens#964]
It is part of `-Wall` with GHC-9.0 it seems.

Alternatives are
- drop pre-GHC-8.0 support and use `import Data.Kind (Type)`
- `#define Type *` for older GHCs

**Comment by RyanGlScott** [comment]
I've been applying `-Wno-star-in-type` in [various places](https://github.com/ekmett/reflection/commit/694bdac087211a908013f626b20b41b3d6e787b3), as it's the most uncontroversial option. I'm not fond of the `#define Type *` approach for the reasons I list [here](https://github.com/ekmett/lens/issues/928#issuecomment-643826999).

> * drop pre-GHC-8.0 support and use `import Data.Kind (Type)`

I'm not necessarily opposed to this idea, but it would be good to develop a consensus that we want to cut off pre-8.0 support before doing this.
