### ISSUE TITLE
Control.Lens.rewriteM does not behave like Data.Generics.Uniplate.Data.rewriteM

### ISSUE THREAD

**Issue by augustss** [ekmett/lens#966]
Is the intention that Lens version of rewriteM should behave the same as Uniplate version?
The result from the Lens version still has places where the rewrite can be applied, whereas Uniplate version does all the rewrites.

If they are intended to be the same, I can make a proper bug report with an example.

**Comment by augustss** [comment]
I just discovered that it's not rewrite, but also things like universe.

**Comment by phadej** [comment]
```haskell
-- | Rewrite by applying a monadic rule everywhere you can. Ensures that the rule cannot be applied anywhere in the result.
rewriteM :: (Monad m, Plated a) => (a -> m (Maybe a)) -> a -> m a
```

=> if something is left out, then something is wrong. It might be your `Plated` instance is wrong, e.g. that `lens`' [`uniplate`](https://hackage.haskell.org/package/lens-4.19.2/docs/Data-Data-Lens.html#v:uniplate) is misbehaving. More information would be welcome.

**Comment by augustss** [comment]
I'm using gplate to define my Plated instances.  I guess they don't do what I expect.
I'm including a simple example that shows the difference.

[Uni.zip](https://github.com/ekmett/lens/files/5817111/Uni.zip)

**Comment by phadej** [comment]
Yes, `gplate` doesn't support mutually recursive types. `Data` is more powerful then `GHC.Generics`. If I change your example with

```diff
+import Data.Data.Lens as L

-instance Plated E where plate = gplate
+instance Plated E where plate = L.uniplate
```

then

```haskell
>>> L.universe e
[EC (CC EA),EA]
```

as with real `uniplate`.

So your options is to either use `uniplate`, or write `plated` manually.  `GHC.Generics` is too weak framework to handle mutually recursive types.

**Comment by augustss** [comment]
I think the documentation should come with a warning about this. It came as
a surprise to me.
