### ISSUE TITLE
Links from wiki to docs broken

### ISSUE THREAD

**Issue by AriFordsham** [ekmett/lens#978]
All the links from the wiki to the docs pooint to ekmett.github.com instead of ekmett.github.io

I'v fixed them [here](https://github.com/AriFordsham/lens-wiki/compare/fix-broken-links) - Wiki repos are akward, there's no direct PR.

**Comment by RyanGlScott** [comment]
Thanks! I went ahead and pushed the changes from https://github.com/AriFordsham/lens-wiki/commit/beba293e8f896c66f31fa7e70466524ac33dd4ed, so I'll go ahead and close this. Please re-open if I messed something up in the process!
