### ISSUE TITLE
Add a function to turn a `Traversal1` into a `Traversal`

### ISSUE THREAD

**Issue by michaelpj** [ekmett/lens#984]
Normally we don't need such a thing due to the typeclass hierarchy, but in the case of `Traversal1`, `Apply` is sadly not a superclass of `Applicative`, so you can't just use a `Traversal1` as a `Traversal`.

It's easy to write a function to do the conversion explicitly, though:
```
traversal1ToTraversal :: Traversal1' a b -> Traversal' a b
traversal1ToTraversal t f = unwrapApplicative . t (WrapApplicative . f)
```

**Comment by phadej** [comment]
I wonder why you need this, everywhere where you use `Traversal` you can use `Traversal1` (given that instantiation type has `Apply` intstance).

**Comment by michaelpj** [comment]
Right, so the reason I need it is that this is in a context where I'm quantifying over `f`. That's why this would normally rely on constraint subsumption rather than just picking a type that satisfies all the constraints.

Specifically, I'm manually defining a `Traversal` for a type which has a sub-structure for which I have a `Traversal1` but not a `Traversal`. Something like this (haven't typechecked):
```
data T1 a = A (Maybe a) | B (T2 a)

-- could also write a Traversal, but that requires duplicating code or using traversal1ToTraversal
t2As :: Traversal1' (T2 a) a

-- Can't be a Traversal1 since the A case can be empty
t1As :: Traversal' (T1 a) a
t1As f = \case
  A ma -> traverse f ma
  B t2 -> (traversal1ToTraversal t2As) f t2
```

Perhaps this is a bit of a corner case, but I do think it's a hole in what you can do with `lens` that you can't convert `Traversal1`s to other optics in a generic context. This function lets you at least get over that hurdle if you happen to hit it.

**Comment by phadej** [comment]
Wouldn't https://hackage.haskell.org/package/lens-5.0.1/docs/Control-Lens-Combinators.html#v:cloneTraversal work in that case?

**Comment by michaelpj** [comment]
Yep, that works. I had no idea what that function did, but apparently it does this :D

I guess then there's nothing to do. Perhaps it's worth a comment in the haddock of `Traversal1` that it doesn't automatically work as a `Traversal` but that `cloneTraversal` will do it? Happy to make a PR>

**Comment by RyanGlScott** [comment]
Sure, I'd happily accept a PR which adds this bit of documentation. (Also, sorry for the late reply.)
